//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Menu
    {
        public AD_Menu()
        {
            this.AD_RoleMenu = new HashSet<AD_RoleMenu>();
        }
    
        public int MenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> MenuParentID { get; set; }
    
        public virtual ICollection<AD_RoleMenu> AD_RoleMenu { get; set; }
    }
}
