//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_RoleMenu
    {
        public int MenuID { get; set; }
        public int RoleID { get; set; }
        public Nullable<bool> AllowAccess { get; set; }
    
        public virtual AD_Menu AD_Menu { get; set; }
        public virtual AD_Roles AD_Roles { get; set; }
    }
}
