//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_User_Kho
    {
        public int USERID { get; set; }
        public long ID_KHO_QLVT { get; set; }
        public long ID_KHO_TTBI { get; set; }
        public long ID_KHO_THUOC { get; set; }
        public string MA_BENHVIEN { get; set; }
    }
}
