//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Users
    {
        public AD_Users()
        {
            this.AD_User_Kho = new HashSet<AD_User_Kho>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> IsSuperUser { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string MA_TINH { get; set; }
        public string MA_HUYEN { get; set; }
    
        public virtual ICollection<AD_User_Kho> AD_User_Kho { get; set; }
    }
}
