//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_KetQuaDT
    {
        public int ID_BC_KetquaDT { get; set; }
        public byte Quy { get; set; }
        public int Nam { get; set; }
        public string DVBaocao { get; set; }
        public string MA_TINH { get; set; }
        public string MA_HUYEN { get; set; }
        public string NguoiBC { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<bool> PTNhap { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<System.DateTime> Ngayhuy { get; set; }
    }
}
