//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_KetQuaDT1
    {
        public int ID_BCKetQuaDT1 { get; set; }
        public int ID_BCKetQuaDT { get; set; }
        public byte ID_Phanloai { get; set; }
        public int Nhom { get; set; }
        public Nullable<int> SoBNDK { get; set; }
        public Nullable<int> Khoi { get; set; }
        public Nullable<int> Hoanthanh { get; set; }
        public Nullable<int> Chet { get; set; }
        public Nullable<int> Thatbai { get; set; }
        public Nullable<int> Bo { get; set; }
        public Nullable<int> Chuyen { get; set; }
        public Nullable<int> Khongdanhgia { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    }
}
