//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_KetQuaDT2
    {
        public int ID_BCKetQuaDT2 { get; set; }
        public int ID_BCKetQuaDT { get; set; }
        public byte Phanloai { get; set; }
        public Nullable<int> XNHIV { get; set; }
        public Nullable<int> DuongHIV { get; set; }
        public Nullable<int> CPT { get; set; }
        public Nullable<int> ARV { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
