//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_KetQuaDTLaoIN
    {
        public byte ID_PHANLOAI { get; set; }
        public string TEN_VUNG { get; set; }
        public string TEN_MIEN { get; set; }
        public string TEN_TINH { get; set; }
        public string TEN_PHANLOAI { get; set; }
        public Nullable<int> KHOI { get; set; }
        public Nullable<int> HOANTHANH { get; set; }
        public Nullable<int> CHET { get; set; }
        public Nullable<int> THATBAI { get; set; }
        public Nullable<int> BOTRI { get; set; }
        public Nullable<int> CHUYEN { get; set; }
        public Nullable<int> KHONGDANHGIA { get; set; }
        public Nullable<int> TONGSOBNDK { get; set; }
    }
}
