//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_ThuNhanBNLao2
    {
        public int ID_BCThunhanBNLaoP2 { get; set; }
        public int ID_BCThunhanBNLao { get; set; }
        public int Phanloai { get; set; }
        public Nullable<int> Nam0 { get; set; }
        public Nullable<int> Nu0 { get; set; }
        public Nullable<int> Nam5 { get; set; }
        public Nullable<int> Nu5 { get; set; }
        public Nullable<int> Nam15 { get; set; }
        public Nullable<int> Nu15 { get; set; }
        public Nullable<int> Nam25 { get; set; }
        public Nullable<int> Nu25 { get; set; }
        public Nullable<int> Nam35 { get; set; }
        public Nullable<int> Nu35 { get; set; }
        public Nullable<int> Nam45 { get; set; }
        public Nullable<int> Nu45 { get; set; }
        public Nullable<int> Nam55 { get; set; }
        public Nullable<int> Nu55 { get; set; }
        public Nullable<int> Nam65 { get; set; }
        public Nullable<int> Nu65 { get; set; }
        public Nullable<bool> HUY { get; set; }
    }
}
