//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_BenhVien
    {
        public long ID_BENHVIEN_KHO { get; set; }
        public string ID_BENHVIEN { get; set; }
        public string TEN_BENHVIEN { get; set; }
        public string DIA_CHI { get; set; }
        public Nullable<int> ID_VUNG { get; set; }
        public string MA_BENHVIEN_CAPTREN { get; set; }
        public Nullable<long> ID_BENHVIEN_CAPTREN { get; set; }
        public Nullable<byte> CAPQUANLY { get; set; }
        public string ID_MATINH { get; set; }
        public string ID_HUYEN { get; set; }
        public Nullable<byte> ID_PHANLOAIYTE { get; set; }
        public Nullable<byte> PHANBIET { get; set; }
        public string ID_LOAIBV { get; set; }
        public Nullable<long> Huy { get; set; }
    }
}
