//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Huyen
    {
        public DM_Huyen()
        {
            this.SO_BenhNhan = new HashSet<SO_BenhNhan>();
        }
    
        public string MA_HUYEN { get; set; }
        public string TEN_HUYEN { get; set; }
        public string MA_TINH { get; set; }
    
        public virtual ICollection<SO_BenhNhan> SO_BenhNhan { get; set; }
    }
}
