//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LoaiBenhVien
    {
        public string ID_LOAIBV { get; set; }
        public string TEN_LOAIBV { get; set; }
        public Nullable<int> THUTU { get; set; }
    }
}
