//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTDT_BenhNhanTuChoiNhanTin
    {
        public long ID { get; set; }
        public long ID_BenhNhan { get; set; }
        public bool TuChoiNhanTinNhanUT { get; set; }
        public bool TuChoiNhanTinNhanXN { get; set; }
        public bool TuChoiNhanTinNhanTT { get; set; }
        public Nullable<System.DateTime> NgayTuChoiTinNhanUT { get; set; }
        public Nullable<System.DateTime> NgayTuChoiTinNhanXN { get; set; }
        public Nullable<System.DateTime> NgayTuChoiTinNhanTT { get; set; }
        public string LyDoTuChoiTinNhanUT { get; set; }
        public string LyDoTuChoiTinNhanXN { get; set; }
        public string LyDoTuChoiTinNhanTT { get; set; }
    }
}
