//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTDT_BenhNhanNhanTinNhan
    {
        public long ID { get; set; }
        public long ID_BenhNhan { get; set; }
        public long ID_SoDieuTri { get; set; }
        public string Sodienthoai { get; set; }
        public string MA_HUYEN { get; set; }
        public System.DateTime NgayGui { get; set; }
        public Nullable<bool> GuiThanhCong { get; set; }
        public Nullable<bool> PhanHoi { get; set; }
        public Nullable<System.DateTime> NgayPhanHoiGanNhat { get; set; }
        public short LoaiTinNhan { get; set; }
        public string TinNhan { get; set; }
        public int Tuan { get; set; }
        public int ID_PhanLoaiBenh { get; set; }
    }
}
