//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTDT_ThongDiepTruyenThong
    {
        public long ID { get; set; }
        public string NoiDung { get; set; }
        public short Loai { get; set; }
        public Nullable<short> GiaiDoan { get; set; }
        public Nullable<short> TuTuan { get; set; }
        public Nullable<short> DenTuan { get; set; }
        public Nullable<short> TanSuat { get; set; }
        public Nullable<short> LoaiTanSuat { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public bool TamDungSuDung { get; set; }
    }
}
