//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTDT_BenhNhanPhanHoiTacDungPhu
    {
        public long ID { get; set; }
        public long ID_BenhNhan { get; set; }
        public long ID_SoDieuTri { get; set; }
        public string Sodienthoai { get; set; }
        public string TacDungPhu { get; set; }
        public System.DateTime NgayNhan { get; set; }
    }
}
