//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTDT_BaoCaoGiamSat
    {
        public long ID { get; set; }
        public long ID_BenhNhan { get; set; }
        public long ID_SoDieuTri { get; set; }
        public string Diachi { get; set; }
        public int Tuoi { get; set; }
        public decimal LieuLuong_E { get; set; }
        public decimal LieuLuong_H { get; set; }
        public decimal LieuLuong_RH { get; set; }
        public decimal LuongCap_E { get; set; }
        public decimal LuongCap_H { get; set; }
        public decimal LuongCap_RH { get; set; }
        public decimal ConLai_E { get; set; }
        public decimal ConLai_H { get; set; }
        public decimal ConLai_RH { get; set; }
        public string Sodienthoai { get; set; }
        public System.DateTime NgayGiamSat { get; set; }
        public System.DateTime NgayCapThuocGanNhat { get; set; }
        public string NhanXetCuaGiamSatVien { get; set; }
        public string DienBienDieuTri { get; set; }
        public string DanDoBenhNhan { get; set; }
        public bool NhapTuMobile { get; set; }
        public System.DateTime NgayNhapBaoCao { get; set; }
    }
}
