//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTDT_ThongKeTinNhan
    {
        public long ID { get; set; }
        public System.DateTime Ngay { get; set; }
        public int SoTinNhanUongThuoc { get; set; }
        public int SoTinNhanTaiKham { get; set; }
        public int SoTinNhanGuiKhac { get; set; }
        public int SoTinNhanPhanHoiUT { get; set; }
        public int SoTinNhanTacDungPhu { get; set; }
        public string MA_HUYEN { get; set; }
    }
}
