//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InDanhSachBenhNhan
    {
        public string SoDKDT { get; set; }
        public string HoTen { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> TuoiNam { get; set; }
        public Nullable<int> TuoiNu { get; set; }
        public string CheDoDieuTri { get; set; }
        public string Ten_PhanLoaiBenh { get; set; }
        public string Ten_PhanLoaiBN { get; set; }
        public string TruocDT { get; set; }
        public string Sau23thang { get; set; }
        public string Sau5thang { get; set; }
        public string Sau78thang { get; set; }
        public string Ten_KetQuaDT { get; set; }
        public long ID_BenhNhan { get; set; }
        public Nullable<long> ID_SoDieuTri { get; set; }
        public Nullable<byte> XNHIV1 { get; set; }
        public Nullable<byte> XNHIV2 { get; set; }
        public Nullable<byte> ART { get; set; }
        public string TenTinhHuyen { get; set; }
        public string MA_HUYEN { get; set; }
        public string MA_TINH { get; set; }
    }
}
