//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InPhieuXetNghiem
    {
        public string SoXN { get; set; }
        public Nullable<int> LydoXN { get; set; }
        public Nullable<byte> SoThangDT { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public byte MauDom { get; set; }
        public Nullable<System.DateTime> NgayNhanMau { get; set; }
        public string TrangThaiDom { get; set; }
        public Nullable<byte> KetQua { get; set; }
        public string HoTen { get; set; }
        public string MaBNQL { get; set; }
        public string SoCMND { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Diachi { get; set; }
        public string NgheNghiep { get; set; }
        public string NoiGioiThieu { get; set; }
        public string BHYT { get; set; }
        public string TEN_HUYEN { get; set; }
        public string TEN_TINH { get; set; }
        public string DonViXetNghiem { get; set; }
        public Nullable<long> ID_PhieuXetNghiem { get; set; }
        public Nullable<long> ID_Benhnhan { get; set; }
    }
}
