//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_THIETBI
    {
        public NTP_CU_THIETBI()
        {
            this.NTP_CU_THIETBI_CHITIET = new HashSet<NTP_CU_THIETBI_CHITIET>();
        }
    
        public decimal ID_BAOCAO { get; set; }
        public int NAM { get; set; }
        public string QUY { get; set; }
        public int NGUOI_TAO { get; set; }
        public System.DateTime NGAY_TAO { get; set; }
        public decimal ID_BENHVIEN_KHO { get; set; }
        public string ID_MATINH { get; set; }
        public int TRANG_THAI { get; set; }
        public Nullable<int> NGUOI_PHEDUYET { get; set; }
        public Nullable<System.DateTime> NGAY_PHEDUYET { get; set; }
    
        public virtual ICollection<NTP_CU_THIETBI_CHITIET> NTP_CU_THIETBI_CHITIET { get; set; }
    }
}
