//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_DM_BV
    {
        public string ID_BENHVIEN { get; set; }
        public string TEN_BENHVIEN { get; set; }
        public string ID_Phanloaiyte { get; set; }
        public string ID_MATINH { get; set; }
        public string ID_HUYEN { get; set; }
        public Nullable<byte> CAPQUANLY { get; set; }
        public int ID_VUNG { get; set; }
    }
}
