//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLTTB_DM_THIETBI
    {
        public NTP_QLTTB_DM_THIETBI()
        {
            this.NTP_QLTTB_KHO = new HashSet<NTP_QLTTB_KHO>();
            this.NTP_QLTTB_KY_KIEMKE_CHITIET = new HashSet<NTP_QLTTB_KY_KIEMKE_CHITIET>();
            this.NTP_QLTTB_PHIEUXUAT_CHITIET = new HashSet<NTP_QLTTB_PHIEUXUAT_CHITIET>();
        }
    
        public int ID_THIETBI { get; set; }
        public string TEN_THIETBI { get; set; }
        public int ID_DVT { get; set; }
        public string MA_NUOC { get; set; }
        public string NHAN_HIEU { get; set; }
        public string MODEL { get; set; }
    
        public virtual NTP_DM_DVT NTP_DM_DVT { get; set; }
        public virtual NTP_DM_NUOC NTP_DM_NUOC { get; set; }
        public virtual ICollection<NTP_QLTTB_KHO> NTP_QLTTB_KHO { get; set; }
        public virtual ICollection<NTP_QLTTB_KY_KIEMKE_CHITIET> NTP_QLTTB_KY_KIEMKE_CHITIET { get; set; }
        public virtual ICollection<NTP_QLTTB_PHIEUXUAT_CHITIET> NTP_QLTTB_PHIEUXUAT_CHITIET { get; set; }
    }
}
