//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_CTCHONGLAOP1
    {
        public int ID_CTChonglaoP1 { get; set; }
        public int ID_CTChonglao { get; set; }
        public bool Phanloai { get; set; }
        public Nullable<int> SoCShienco { get; set; }
        public Nullable<int> SoCSTrienkhai { get; set; }
        public Nullable<int> DiemkinhTT { get; set; }
        public Nullable<int> DiemkinhKD { get; set; }
        public Nullable<int> XNNC { get; set; }
        public Nullable<int> XNKSD { get; set; }
        public Nullable<int> TuvanHIV { get; set; }
        public Nullable<int> CungcapART { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
