//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_DM_NUOC
    {
        public NTP_DM_NUOC()
        {
            this.NTP_QLTTB_DM_THIETBI = new HashSet<NTP_QLTTB_DM_THIETBI>();
        }
    
        public string MA_NUOC { get; set; }
        public string TEN_NUOC { get; set; }
    
        public virtual ICollection<NTP_QLTTB_DM_THIETBI> NTP_QLTTB_DM_THIETBI { get; set; }
    }
}
