//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_VT_EXPORT
    {
        public decimal ID_EXPORT { get; set; }
        public long ID_KHO { get; set; }
        public int ID_VATTU { get; set; }
        public string ID_NGUONKINHPHI { get; set; }
        public Nullable<long> ID_KHO_NHAN { get; set; }
        public System.DateTime NGAY_XUAT_KHO { get; set; }
        public int LOAI_XUAT { get; set; }
        public decimal SO_LUONG { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NGUOI_NM { get; set; }
        public int TRANG_THAI { get; set; }
        public string MA_PHIEU { get; set; }
        public string NGUOI_VIETPHIEU { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
    }
}
