//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_CTCHONGLAOP2
    {
        public int ID_CTChonglaoP2 { get; set; }
        public int ID_CTChonglao { get; set; }
        public long LoaihinhYte { get; set; }
        public Nullable<int> DuocChuyen { get; set; }
        public Nullable<int> Chandoan { get; set; }
        public Nullable<int> DieuTri { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
