//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_DM_VATTU
    {
        public NTP_QLVT_DM_VATTU()
        {
            this.NTP_QLVT_KHO = new HashSet<NTP_QLVT_KHO>();
            this.NTP_QLVT_KIEMKE_CHITIET = new HashSet<NTP_QLVT_KIEMKE_CHITIET>();
            this.NTP_QLVT_KY_KIEMKE_CHITIET = new HashSet<NTP_QLVT_KY_KIEMKE_CHITIET>();
            this.NTP_QLVT_PHIEUNHAP_CHITIET = new HashSet<NTP_QLVT_PHIEUNHAP_CHITIET>();
            this.NTP_QLVT_PHIEUXUAT_CHITIET = new HashSet<NTP_QLVT_PHIEUXUAT_CHITIET>();
        }
    
        public int ID_VATTU { get; set; }
        public string TEN_VATTU { get; set; }
        public int ID_DVT { get; set; }
        public int TYPE { get; set; }
        public string MA_NUOC { get; set; }
    
        public virtual ICollection<NTP_QLVT_KHO> NTP_QLVT_KHO { get; set; }
        public virtual ICollection<NTP_QLVT_KIEMKE_CHITIET> NTP_QLVT_KIEMKE_CHITIET { get; set; }
        public virtual ICollection<NTP_QLVT_KY_KIEMKE_CHITIET> NTP_QLVT_KY_KIEMKE_CHITIET { get; set; }
        public virtual ICollection<NTP_QLVT_PHIEUNHAP_CHITIET> NTP_QLVT_PHIEUNHAP_CHITIET { get; set; }
        public virtual ICollection<NTP_QLVT_PHIEUXUAT_CHITIET> NTP_QLVT_PHIEUXUAT_CHITIET { get; set; }
    }
}
