//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_DM_THUOC
    {
        public NTP_DM_THUOC()
        {
            this.NTP_QLT_KHOTHUOC = new HashSet<NTP_QLT_KHOTHUOC>();
            this.NTP_QLT_KIEMKE_CHITIET = new HashSet<NTP_QLT_KIEMKE_CHITIET>();
            this.NTP_QLT_PHIEUXUAT_CHITIET = new HashSet<NTP_QLT_PHIEUXUAT_CHITIET>();
        }
    
        public long ID_THUOC { get; set; }
        public string MA_THUOC { get; set; }
        public string TEN_THUOC { get; set; }
        public string HAM_LUONG { get; set; }
        public string MA_NUOC { get; set; }
        public int ID_DVT { get; set; }
    
        public virtual NTP_DM_DVT NTP_DM_DVT { get; set; }
        public virtual ICollection<NTP_QLT_KHOTHUOC> NTP_QLT_KHOTHUOC { get; set; }
        public virtual ICollection<NTP_QLT_KIEMKE_CHITIET> NTP_QLT_KIEMKE_CHITIET { get; set; }
        public virtual ICollection<NTP_QLT_PHIEUXUAT_CHITIET> NTP_QLT_PHIEUXUAT_CHITIET { get; set; }
    }
}
