//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_PHIEUCHUYEN1
    {
        public int ID_Phieuchuyen { get; set; }
        public int ID_Dieutri { get; set; }
        public Nullable<byte> PhanLoai { get; set; }
        public string DVChuyen { get; set; }
        public string DVTiepnhan { get; set; }
        public Nullable<int> IDDieutri_DVTN { get; set; }
        public string TinhTrangBN { get; set; }
        public string Lydo { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
        public string SoDKDT { get; set; }
        public byte Tiepnhan { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NGUOI_NM { get; set; }
    }
}
