//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_THUOC
    {
        public int ID_Thuoc { get; set; }
        public Nullable<int> ID_Dieutri { get; set; }
        public Nullable<System.DateTime> NgayDT { get; set; }
        public Nullable<int> ID_PhacdoDT { get; set; }
        public string PhacDoKhac { get; set; }
        public Nullable<bool> GiaidoanDT { get; set; }
        public Nullable<System.DateTime> Tungay { get; set; }
        public Nullable<byte> RHZE { get; set; }
        public Nullable<byte> RHZ { get; set; }
        public Nullable<byte> RHE { get; set; }
        public Nullable<byte> RH { get; set; }
        public Nullable<byte> EH { get; set; }
        public Nullable<byte> E { get; set; }
        public Nullable<byte> H { get; set; }
        public Nullable<byte> Z { get; set; }
        public Nullable<byte> S { get; set; }
        public string TLaoKhac { get; set; }
        public Nullable<byte> Cotrimoxazole { get; set; }
        public string ART { get; set; }
        public string Khac { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NGUOI_NM { get; set; }
    }
}
