//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_SURVEY_QUESTION
    {
        public NTP_SURVEY_QUESTION()
        {
            this.NTP_SURVEY_OPTION = new HashSet<NTP_SURVEY_OPTION>();
        }
    
        public decimal QUESTION_ID { get; set; }
        public string QUESTION_CONTENT { get; set; }
        public decimal SURVEY_ID { get; set; }
        public int OPTION_TYPE { get; set; }
        public int VIEW_ORDER { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public int CREATED_USER { get; set; }
    
        public virtual ICollection<NTP_SURVEY_OPTION> NTP_SURVEY_OPTION { get; set; }
        public virtual NTP_SURVEYS NTP_SURVEYS { get; set; }
    }
}
