//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_DM_TINH
    {
        public NTP_DM_TINH()
        {
            this.NTP_DM_HUYEN = new HashSet<NTP_DM_HUYEN>();
            this.NTP_QLVT_DM_KHO = new HashSet<NTP_QLVT_DM_KHO>();
        }
    
        public string MA_TINH { get; set; }
        public string TEN_TINH { get; set; }
        public int ID_VUNG { get; set; }
        public Nullable<int> ID_MIEN { get; set; }
        public Nullable<int> DANSO { get; set; }
    
        public virtual ICollection<NTP_DM_HUYEN> NTP_DM_HUYEN { get; set; }
        public virtual NTP_DM_VUNG NTP_DM_VUNG { get; set; }
        public virtual ICollection<NTP_QLVT_DM_KHO> NTP_QLVT_DM_KHO { get; set; }
    }
}
