//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NTP_OLDEntities : DbContext
    {
        public NTP_OLDEntities()
            : base("name=NTP_OLDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NTP_BN_BC_KETQUADT> NTP_BN_BC_KETQUADT { get; set; }
        public virtual DbSet<NTP_BN_BC_KetquaDTp1> NTP_BN_BC_KetquaDTp1 { get; set; }
        public virtual DbSet<NTP_BN_BC_KETQUADTP2> NTP_BN_BC_KETQUADTP2 { get; set; }
        public virtual DbSet<NTP_BN_BC_KETQUAXN> NTP_BN_BC_KETQUAXN { get; set; }
        public virtual DbSet<NTP_BN_BC_THUNHANBNLAO> NTP_BN_BC_THUNHANBNLAO { get; set; }
        public virtual DbSet<NTP_BN_BC_THUNHANBNLAOP1> NTP_BN_BC_THUNHANBNLAOP1 { get; set; }
        public virtual DbSet<NTP_BN_BC_THUNHANBNLAOP2> NTP_BN_BC_THUNHANBNLAOP2 { get; set; }
        public virtual DbSet<NTP_BN_BCKETQUADIEUTRILAOIN> NTP_BN_BCKETQUADIEUTRILAOIN { get; set; }
        public virtual DbSet<NTP_BN_BENHNHAN> NTP_BN_BENHNHAN { get; set; }
        public virtual DbSet<NTP_BN_CTCHONGLAO> NTP_BN_CTCHONGLAO { get; set; }
        public virtual DbSet<NTP_BN_CTCHONGLAOP1> NTP_BN_CTCHONGLAOP1 { get; set; }
        public virtual DbSet<NTP_BN_CTCHONGLAOP2> NTP_BN_CTCHONGLAOP2 { get; set; }
        public virtual DbSet<NTP_BN_CTCHONGLAOP3> NTP_BN_CTCHONGLAOP3 { get; set; }
        public virtual DbSet<NTP_BN_DIEUTRI> NTP_BN_DIEUTRI { get; set; }
        public virtual DbSet<NTP_BN_DM_DOITUONG> NTP_BN_DM_DOITUONG { get; set; }
        public virtual DbSet<NTP_BN_DM_KETQUADT> NTP_BN_DM_KETQUADT { get; set; }
        public virtual DbSet<NTP_BN_DM_KETQUAXN> NTP_BN_DM_KETQUAXN { get; set; }
        public virtual DbSet<NTP_BN_DM_NGUONNHANLUC> NTP_BN_DM_NGUONNHANLUC { get; set; }
        public virtual DbSet<NTP_BN_DM_PHACDODT> NTP_BN_DM_PHACDODT { get; set; }
        public virtual DbSet<NTP_BN_DM_PHANLOAIBENH> NTP_BN_DM_PHANLOAIBENH { get; set; }
        public virtual DbSet<NTP_BN_DM_PHANLOAIBN> NTP_BN_DM_PHANLOAIBN { get; set; }
        public virtual DbSet<NTP_BN_DM_PHANLOAIYTE> NTP_BN_DM_PHANLOAIYTE { get; set; }
        public virtual DbSet<NTP_BN_DMPHANLOAIBN_BC> NTP_BN_DMPHANLOAIBN_BC { get; set; }
        public virtual DbSet<NTP_BN_PHANHOI> NTP_BN_PHANHOI { get; set; }
        public virtual DbSet<NTP_BN_PHIEUCHUYEN> NTP_BN_PHIEUCHUYEN { get; set; }
        public virtual DbSet<NTP_BN_PHIEUXETNGHIEM> NTP_BN_PHIEUXETNGHIEM { get; set; }
        public virtual DbSet<NTP_BN_PHIEUXETNGHIEM_C> NTP_BN_PHIEUXETNGHIEM_C { get; set; }
        public virtual DbSet<NTP_BN_THUOC> NTP_BN_THUOC { get; set; }
        public virtual DbSet<NTP_BN_TINHHINHTRIENKHAICTCL> NTP_BN_TINHHINHTRIENKHAICTCL { get; set; }
        public virtual DbSet<NTP_BN_XETNGHIEM_GD> NTP_BN_XETNGHIEM_GD { get; set; }
        public virtual DbSet<NTP_BN_XETNGHIEM_GE> NTP_BN_XETNGHIEM_GE { get; set; }
        public virtual DbSet<NTP_CU_HC_EXPORT> NTP_CU_HC_EXPORT { get; set; }
        public virtual DbSet<NTP_CU_HC_IMPORT> NTP_CU_HC_IMPORT { get; set; }
        public virtual DbSet<NTP_CU_HC_TH_KHO> NTP_CU_HC_TH_KHO { get; set; }
        public virtual DbSet<NTP_CU_HC_TH_NHAPXUAT> NTP_CU_HC_TH_NHAPXUAT { get; set; }
        public virtual DbSet<NTP_CU_SUDUNGTHUOC> NTP_CU_SUDUNGTHUOC { get; set; }
        public virtual DbSet<NTP_CU_SUDUNGTHUOC_CHITIET> NTP_CU_SUDUNGTHUOC_CHITIET { get; set; }
        public virtual DbSet<NTP_CU_THIETBI> NTP_CU_THIETBI { get; set; }
        public virtual DbSet<NTP_CU_THIETBI_CHITIET> NTP_CU_THIETBI_CHITIET { get; set; }
        public virtual DbSet<NTP_CU_THUOC_EXPORT> NTP_CU_THUOC_EXPORT { get; set; }
        public virtual DbSet<NTP_CU_THUOC_IMPORT> NTP_CU_THUOC_IMPORT { get; set; }
        public virtual DbSet<NTP_CU_THUOC_TH_KHO> NTP_CU_THUOC_TH_KHO { get; set; }
        public virtual DbSet<NTP_CU_THUOC_TH_NHAPXUAT> NTP_CU_THUOC_TH_NHAPXUAT { get; set; }
        public virtual DbSet<NTP_CU_TTB_EXPORT> NTP_CU_TTB_EXPORT { get; set; }
        public virtual DbSet<NTP_CU_TTB_IMPORT> NTP_CU_TTB_IMPORT { get; set; }
        public virtual DbSet<NTP_CU_TTB_TH_KHO> NTP_CU_TTB_TH_KHO { get; set; }
        public virtual DbSet<NTP_CU_TTB_TH_NHAPXUAT> NTP_CU_TTB_TH_NHAPXUAT { get; set; }
        public virtual DbSet<NTP_CU_VATTUHOACHAT> NTP_CU_VATTUHOACHAT { get; set; }
        public virtual DbSet<NTP_CU_VATTUHOACHAT_HC> NTP_CU_VATTUHOACHAT_HC { get; set; }
        public virtual DbSet<NTP_CU_VATTUHOACHAT_VT> NTP_CU_VATTUHOACHAT_VT { get; set; }
        public virtual DbSet<NTP_CU_VT_EXPORT> NTP_CU_VT_EXPORT { get; set; }
        public virtual DbSet<NTP_CU_VT_IMPORT> NTP_CU_VT_IMPORT { get; set; }
        public virtual DbSet<NTP_CU_VT_TH_KHO> NTP_CU_VT_TH_KHO { get; set; }
        public virtual DbSet<NTP_CU_VT_TH_NHAPXUAT> NTP_CU_VT_TH_NHAPXUAT { get; set; }
        public virtual DbSet<NTP_DM_BENHVIEN> NTP_DM_BENHVIEN { get; set; }
        public virtual DbSet<NTP_DM_BV> NTP_DM_BV { get; set; }
        public virtual DbSet<NTP_DM_CAP> NTP_DM_CAP { get; set; }
        public virtual DbSet<NTP_DM_DVT> NTP_DM_DVT { get; set; }
        public virtual DbSet<NTP_DM_HANG> NTP_DM_HANG { get; set; }
        public virtual DbSet<NTP_DM_HUYEN> NTP_DM_HUYEN { get; set; }
        public virtual DbSet<NTP_DM_LOAIBV> NTP_DM_LOAIBV { get; set; }
        public virtual DbSet<NTP_DM_LYDO_NHAPXUAT> NTP_DM_LYDO_NHAPXUAT { get; set; }
        public virtual DbSet<NTP_DM_MIEN> NTP_DM_MIEN { get; set; }
        public virtual DbSet<NTP_DM_NGUONKINHPHI> NTP_DM_NGUONKINHPHI { get; set; }
        public virtual DbSet<NTP_DM_NUOC> NTP_DM_NUOC { get; set; }
        public virtual DbSet<NTP_DM_THUOC> NTP_DM_THUOC { get; set; }
        public virtual DbSet<NTP_DM_TINH> NTP_DM_TINH { get; set; }
        public virtual DbSet<NTP_DM_VUNG> NTP_DM_VUNG { get; set; }
        public virtual DbSet<NTP_KD_BC_HOATDONGXN> NTP_KD_BC_HOATDONGXN { get; set; }
        public virtual DbSet<NTP_KD_BC_HOATDONGXNC> NTP_KD_BC_HOATDONGXNC { get; set; }
        public virtual DbSet<NTP_KD_BC_KIEMDINHTB> NTP_KD_BC_KIEMDINHTB { get; set; }
        public virtual DbSet<NTP_KD_PLAYMAU> NTP_KD_PLAYMAU { get; set; }
        public virtual DbSet<NTP_KD_PLAYMAU_C> NTP_KD_PLAYMAU_C { get; set; }
        public virtual DbSet<NTP_NEWS> NTP_NEWS { get; set; }
        public virtual DbSet<NTP_QLT_DM_KHOTHUOC> NTP_QLT_DM_KHOTHUOC { get; set; }
        public virtual DbSet<NTP_QLT_DM_TRANGTHAI> NTP_QLT_DM_TRANGTHAI { get; set; }
        public virtual DbSet<NTP_QLT_KIEMKE> NTP_QLT_KIEMKE { get; set; }
        public virtual DbSet<NTP_QLT_KIEMKE_CHITIET> NTP_QLT_KIEMKE_CHITIET { get; set; }
        public virtual DbSet<NTP_QLT_KY_KIEMKE> NTP_QLT_KY_KIEMKE { get; set; }
        public virtual DbSet<NTP_QLT_KY_KIEMKE_CHITIET> NTP_QLT_KY_KIEMKE_CHITIET { get; set; }
        public virtual DbSet<NTP_QLT_PHIEUNHAP> NTP_QLT_PHIEUNHAP { get; set; }
        public virtual DbSet<NTP_QLT_PHIEUNHAP_CHITIET> NTP_QLT_PHIEUNHAP_CHITIET { get; set; }
        public virtual DbSet<NTP_QLT_PHIEUXUAT> NTP_QLT_PHIEUXUAT { get; set; }
        public virtual DbSet<NTP_QLT_PHIEUXUAT_CHITIET> NTP_QLT_PHIEUXUAT_CHITIET { get; set; }
        public virtual DbSet<NTP_QLTTB_DM_KHO> NTP_QLTTB_DM_KHO { get; set; }
        public virtual DbSet<NTP_QLTTB_DM_THIETBI> NTP_QLTTB_DM_THIETBI { get; set; }
        public virtual DbSet<NTP_QLTTB_DM_TRANGTHAI> NTP_QLTTB_DM_TRANGTHAI { get; set; }
        public virtual DbSet<NTP_QLTTB_KIEMKE> NTP_QLTTB_KIEMKE { get; set; }
        public virtual DbSet<NTP_QLTTB_KIEMKE_CHITIET> NTP_QLTTB_KIEMKE_CHITIET { get; set; }
        public virtual DbSet<NTP_QLTTB_KY_KIEMKE> NTP_QLTTB_KY_KIEMKE { get; set; }
        public virtual DbSet<NTP_QLTTB_KY_KIEMKE_CHITIET> NTP_QLTTB_KY_KIEMKE_CHITIET { get; set; }
        public virtual DbSet<NTP_QLTTB_PHIEUNHAP> NTP_QLTTB_PHIEUNHAP { get; set; }
        public virtual DbSet<NTP_QLTTB_PHIEUNHAP_CHITIET> NTP_QLTTB_PHIEUNHAP_CHITIET { get; set; }
        public virtual DbSet<NTP_QLTTB_PHIEUXUAT> NTP_QLTTB_PHIEUXUAT { get; set; }
        public virtual DbSet<NTP_QLTTB_PHIEUXUAT_CHITIET> NTP_QLTTB_PHIEUXUAT_CHITIET { get; set; }
        public virtual DbSet<NTP_QLVT_DM_KHO> NTP_QLVT_DM_KHO { get; set; }
        public virtual DbSet<NTP_QLVT_DM_TRANGTHAI> NTP_QLVT_DM_TRANGTHAI { get; set; }
        public virtual DbSet<NTP_QLVT_DM_VATTU> NTP_QLVT_DM_VATTU { get; set; }
        public virtual DbSet<NTP_QLVT_KIEMKE> NTP_QLVT_KIEMKE { get; set; }
        public virtual DbSet<NTP_QLVT_KIEMKE_CHITIET> NTP_QLVT_KIEMKE_CHITIET { get; set; }
        public virtual DbSet<NTP_QLVT_KY_KIEMKE> NTP_QLVT_KY_KIEMKE { get; set; }
        public virtual DbSet<NTP_QLVT_KY_KIEMKE_CHITIET> NTP_QLVT_KY_KIEMKE_CHITIET { get; set; }
        public virtual DbSet<NTP_QLVT_PHIEUNHAP> NTP_QLVT_PHIEUNHAP { get; set; }
        public virtual DbSet<NTP_QLVT_PHIEUNHAP_CHITIET> NTP_QLVT_PHIEUNHAP_CHITIET { get; set; }
        public virtual DbSet<NTP_QLVT_PHIEUXUAT> NTP_QLVT_PHIEUXUAT { get; set; }
        public virtual DbSet<NTP_QLVT_PHIEUXUAT_CHITIET> NTP_QLVT_PHIEUXUAT_CHITIET { get; set; }
        public virtual DbSet<NTP_SURVEY_OPTION> NTP_SURVEY_OPTION { get; set; }
        public virtual DbSet<NTP_SURVEY_QUESTION> NTP_SURVEY_QUESTION { get; set; }
        public virtual DbSet<NTP_SURVEY_RESULT> NTP_SURVEY_RESULT { get; set; }
        public virtual DbSet<NTP_SURVEYS> NTP_SURVEYS { get; set; }
        public virtual DbSet<NTP_BN_BC_KetquaDTp1_tmp> NTP_BN_BC_KetquaDTp1_tmp { get; set; }
        public virtual DbSet<NTP_BN_BCTHUNHAN> NTP_BN_BCTHUNHAN { get; set; }
        public virtual DbSet<NTP_BN_BCTHUNHAN_LAOHIV> NTP_BN_BCTHUNHAN_LAOHIV { get; set; }
        public virtual DbSet<NTP_BN_KQDT> NTP_BN_KQDT { get; set; }
        public virtual DbSet<NTP_BN_PHIEUCHUYEN1> NTP_BN_PHIEUCHUYEN1 { get; set; }
        public virtual DbSet<NTP_DM_USER_KHO> NTP_DM_USER_KHO { get; set; }
        public virtual DbSet<NTP_QLT_KHOTHUOC> NTP_QLT_KHOTHUOC { get; set; }
        public virtual DbSet<NTP_QLTTB_KHO> NTP_QLTTB_KHO { get; set; }
        public virtual DbSet<NTP_QLVT_KHO> NTP_QLVT_KHO { get; set; }
        public virtual DbSet<NTP_TEST> NTP_TEST { get; set; }
        public virtual DbSet<NTP_TEST1> NTP_TEST1 { get; set; }
        public virtual DbSet<NTP_TEST2> NTP_TEST2 { get; set; }
        public virtual DbSet<PHIEUXETNGHIEM_C> PHIEUXETNGHIEM_C { get; set; }
        public virtual DbSet<PHIEUXN> PHIEUXNs { get; set; }
        public virtual DbSet<PHIEUXN_C> PHIEUXN_C { get; set; }
        public virtual DbSet<PXN1> PXN1 { get; set; }
        public virtual DbSet<PXN2> PXN2 { get; set; }
        public virtual DbSet<NTP_QLTB_View_XuatNhap> NTP_QLTB_View_XuatNhap { get; set; }
        public virtual DbSet<NTP_QLVT_VW_ALL_NHAPXUAT> NTP_QLVT_VW_ALL_NHAPXUAT { get; set; }
        public virtual DbSet<NTP_QLVT_VW_PHIEUNHAP_TONGHOP> NTP_QLVT_VW_PHIEUNHAP_TONGHOP { get; set; }
        public virtual DbSet<NTP_QLVT_VW_PHIEUXUAT_TONGHOP> NTP_QLVT_VW_PHIEUXUAT_TONGHOP { get; set; }
    
        public virtual int NTP_BN_BCKETQUAAMHOADOM_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUAAMHOADOM_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCKETQUAAMHOADOMBYHUYEN_IN(string tINH, Nullable<int> mIEN, Nullable<int> vUNG, Nullable<int> nAM, string qUY, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(int));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUAAMHOADOMBYHUYEN_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCKETQUADIEUTRILAO_IN(string tINH, Nullable<int> mIEN, Nullable<int> vUNG, Nullable<int> nAM, string qUY, Nullable<byte> loaiBC, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(int));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var loaiBCParameter = loaiBC.HasValue ?
                new ObjectParameter("LoaiBC", loaiBC) :
                new ObjectParameter("LoaiBC", typeof(byte));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUADIEUTRILAO_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, loaiBCParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCKETQUADIEUTRILAOBYHUYEN_IN(string tINH, Nullable<int> mIEN, Nullable<int> vUNG, Nullable<int> nAM, string qUY, Nullable<byte> loaiBC, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(int));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var loaiBCParameter = loaiBC.HasValue ?
                new ObjectParameter("LoaiBC", loaiBC) :
                new ObjectParameter("LoaiBC", typeof(byte));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUADIEUTRILAOBYHUYEN_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, loaiBCParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCKETQUADT_TUYENHUYEN(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, Nullable<int> nAM, Nullable<byte> qUY, string dVBAOCAO, Nullable<byte> cAPNHATDL)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            var cAPNHATDLParameter = cAPNHATDL.HasValue ?
                new ObjectParameter("CAPNHATDL", cAPNHATDL) :
                new ObjectParameter("CAPNHATDL", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUADT_TUYENHUYEN", tUNGAYParameter, dENNGAYParameter, nAMParameter, qUYParameter, dVBAOCAOParameter, cAPNHATDLParameter);
        }
    
        public virtual int NTP_BN_BCKETQUADTCHUNGCACTHE_IN(string tINH, Nullable<int> mIEN, Nullable<int> vUNG, Nullable<int> nAM, string qUY)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(int));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUADTCHUNGCACTHE_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter);
        }
    
        public virtual int NTP_BN_BCKETQUAXN_TUYENHUYEN(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, Nullable<int> nAM, Nullable<byte> qUY, string dVBAOCAO, Nullable<byte> cAPNHATDL)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            var cAPNHATDLParameter = cAPNHATDL.HasValue ?
                new ObjectParameter("CAPNHATDL", cAPNHATDL) :
                new ObjectParameter("CAPNHATDL", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCKETQUAXN_TUYENHUYEN", tUNGAYParameter, dENNGAYParameter, nAMParameter, qUYParameter, dVBAOCAOParameter, cAPNHATDLParameter);
        }
    
        public virtual int NTP_BN_BCNHANLUCTHAMGIACTCL_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, Nullable<byte> pHANLOAIBC)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var pHANLOAIBCParameter = pHANLOAIBC.HasValue ?
                new ObjectParameter("PHANLOAIBC", pHANLOAIBC) :
                new ObjectParameter("PHANLOAIBC", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCNHANLUCTHAMGIACTCL_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, pHANLOAIBCParameter);
        }
    
        public virtual int NTP_BN_BCTHAMGIAYTETRONGCTCL_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHAMGIAYTETRONGCTCL_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter);
        }
    
        public virtual int NTP_BN_BCTHAMGIAYTETRONGHDCHANDOAN_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHAMGIAYTETRONGHDCHANDOAN_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter);
        }
    
        public virtual int NTP_BN_BCTHAMGIAYTETRONGHDPHATHIEN_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, Nullable<byte> pHANLOAIBC)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var pHANLOAIBCParameter = pHANLOAIBC.HasValue ?
                new ObjectParameter("PHANLOAIBC", pHANLOAIBC) :
                new ObjectParameter("PHANLOAIBC", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHAMGIAYTETRONGHDPHATHIEN_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, pHANLOAIBCParameter);
        }
    
        public virtual int NTP_BN_BCTHUNHANBNLAO_IN(Nullable<byte> pHANLOAIBC, string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, string dK)
        {
            var pHANLOAIBCParameter = pHANLOAIBC.HasValue ?
                new ObjectParameter("PHANLOAIBC", pHANLOAIBC) :
                new ObjectParameter("PHANLOAIBC", typeof(byte));
    
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHUNHANBNLAO_IN", pHANLOAIBCParameter, tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCTHUNHANBNLAO_TREEM(Nullable<byte> pHANLOAIBC, string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, string dK)
        {
            var pHANLOAIBCParameter = pHANLOAIBC.HasValue ?
                new ObjectParameter("PHANLOAIBC", pHANLOAIBC) :
                new ObjectParameter("PHANLOAIBC", typeof(byte));
    
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHUNHANBNLAO_TREEM", pHANLOAIBCParameter, tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCThunhanBNLao_TUYENHUYEN(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, Nullable<int> nAM, Nullable<byte> qUY, string dVBAOCAO, Nullable<byte> cAPNHATDL)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            var cAPNHATDLParameter = cAPNHATDL.HasValue ?
                new ObjectParameter("CAPNHATDL", cAPNHATDL) :
                new ObjectParameter("CAPNHATDL", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCThunhanBNLao_TUYENHUYEN", tUNGAYParameter, dENNGAYParameter, nAMParameter, qUYParameter, dVBAOCAOParameter, cAPNHATDLParameter);
        }
    
        public virtual int NTP_BN_BCTHUNHANBNLAOBYHUYEN_IN(Nullable<byte> pHANLOAIBC, string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, string dK)
        {
            var pHANLOAIBCParameter = pHANLOAIBC.HasValue ?
                new ObjectParameter("PHANLOAIBC", pHANLOAIBC) :
                new ObjectParameter("PHANLOAIBC", typeof(byte));
    
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHUNHANBNLAOBYHUYEN_IN", pHANLOAIBCParameter, tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, dKParameter);
        }
    
        public virtual int NTP_BN_BCTHUNHANBNLAONGOAIPHOI_IN(string tINH, Nullable<int> mIEN, Nullable<int> vUNG, Nullable<int> nAM, string qUY)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(int));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHUNHANBNLAONGOAIPHOI_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter);
        }
    
        public virtual int NTP_BN_BCTHUNHANBNLAOTHEOTUOIGIOI_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, Nullable<byte> phanloaiBC)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var phanloaiBCParameter = phanloaiBC.HasValue ?
                new ObjectParameter("phanloaiBC", phanloaiBC) :
                new ObjectParameter("phanloaiBC", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTHUNHANBNLAOTHEOTUOIGIOI_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, phanloaiBCParameter);
        }
    
        public virtual int NTP_BN_BCTINHHINHNHANLUCTHAMGIAPCL_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, Nullable<byte> pHANLOAIBC)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var pHANLOAIBCParameter = pHANLOAIBC.HasValue ?
                new ObjectParameter("PHANLOAIBC", pHANLOAIBC) :
                new ObjectParameter("PHANLOAIBC", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTINHHINHNHANLUCTHAMGIAPCL_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, pHANLOAIBCParameter);
        }
    
        public virtual int NTP_BN_BCTONGHOPTUYENHUYEN_IN(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, Nullable<int> nAM, string qUY, string dVBAOCAO, Nullable<byte> lOAIBC, Nullable<byte> cAPIN, Nullable<byte> cAPNHATDL)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            var lOAIBCParameter = lOAIBC.HasValue ?
                new ObjectParameter("LOAIBC", lOAIBC) :
                new ObjectParameter("LOAIBC", typeof(byte));
    
            var cAPINParameter = cAPIN.HasValue ?
                new ObjectParameter("CAPIN", cAPIN) :
                new ObjectParameter("CAPIN", typeof(byte));
    
            var cAPNHATDLParameter = cAPNHATDL.HasValue ?
                new ObjectParameter("CAPNHATDL", cAPNHATDL) :
                new ObjectParameter("CAPNHATDL", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTONGHOPTUYENHUYEN_IN", tUNGAYParameter, dENNGAYParameter, nAMParameter, qUYParameter, dVBAOCAOParameter, lOAIBCParameter, cAPINParameter, cAPNHATDLParameter);
        }
    
        public virtual int NTP_BN_BCTONGHOPTUYENTINH_IN(string tINH, Nullable<int> nAM, string qUY, Nullable<byte> phanloaiBC, string dVBAOCAO)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var phanloaiBCParameter = phanloaiBC.HasValue ?
                new ObjectParameter("phanloaiBC", phanloaiBC) :
                new ObjectParameter("phanloaiBC", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BCTONGHOPTUYENTINH_IN", tINHParameter, nAMParameter, qUYParameter, phanloaiBCParameter, dVBAOCAOParameter);
        }
    
        public virtual int NTP_BN_BENHNHAN_BY_DONVIDIEUTRI(Nullable<byte> mRavien, string diachi, string mThangNam, string maBN, string hoten, string soCMT, string dVDieutri)
        {
            var mRavienParameter = mRavien.HasValue ?
                new ObjectParameter("mRavien", mRavien) :
                new ObjectParameter("mRavien", typeof(byte));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var mThangNamParameter = mThangNam != null ?
                new ObjectParameter("mThangNam", mThangNam) :
                new ObjectParameter("mThangNam", typeof(string));
    
            var maBNParameter = maBN != null ?
                new ObjectParameter("MaBN", maBN) :
                new ObjectParameter("MaBN", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var soCMTParameter = soCMT != null ?
                new ObjectParameter("SoCMT", soCMT) :
                new ObjectParameter("SoCMT", typeof(string));
    
            var dVDieutriParameter = dVDieutri != null ?
                new ObjectParameter("DVDieutri", dVDieutri) :
                new ObjectParameter("DVDieutri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_BENHNHAN_BY_DONVIDIEUTRI", mRavienParameter, diachiParameter, mThangNamParameter, maBNParameter, hotenParameter, soCMTParameter, dVDieutriParameter);
        }
    
        public virtual ObjectResult<NTP_BN_BENHNHAN_DANGDIEUTRI_Result> NTP_BN_BENHNHAN_DANGDIEUTRI(string mID_Benhnhan)
        {
            var mID_BenhnhanParameter = mID_Benhnhan != null ?
                new ObjectParameter("mID_Benhnhan", mID_Benhnhan) :
                new ObjectParameter("mID_Benhnhan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_BN_BENHNHAN_DANGDIEUTRI_Result>("NTP_BN_BENHNHAN_DANGDIEUTRI", mID_BenhnhanParameter);
        }
    
        public virtual ObjectResult<string> NTP_BN_BENHNHAN_DELETED(string mID_Benhnhan, string nguoi_SD)
        {
            var mID_BenhnhanParameter = mID_Benhnhan != null ?
                new ObjectParameter("mID_Benhnhan", mID_Benhnhan) :
                new ObjectParameter("mID_Benhnhan", typeof(string));
    
            var nguoi_SDParameter = nguoi_SD != null ?
                new ObjectParameter("Nguoi_SD", nguoi_SD) :
                new ObjectParameter("Nguoi_SD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("NTP_BN_BENHNHAN_DELETED", mID_BenhnhanParameter, nguoi_SDParameter);
        }
    
        public virtual int NTP_BN_DIEUTRI_DANHSACHBNDIEUTRI(string mATinh, string dVDieutri, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, Nullable<byte> xacnhanBN, string dieukien)
        {
            var mATinhParameter = mATinh != null ?
                new ObjectParameter("MATinh", mATinh) :
                new ObjectParameter("MATinh", typeof(string));
    
            var dVDieutriParameter = dVDieutri != null ?
                new ObjectParameter("DVDieutri", dVDieutri) :
                new ObjectParameter("DVDieutri", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var xacnhanBNParameter = xacnhanBN.HasValue ?
                new ObjectParameter("xacnhanBN", xacnhanBN) :
                new ObjectParameter("xacnhanBN", typeof(byte));
    
            var dieukienParameter = dieukien != null ?
                new ObjectParameter("Dieukien", dieukien) :
                new ObjectParameter("Dieukien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_DIEUTRI_DANHSACHBNDIEUTRI", mATinhParameter, dVDieutriParameter, tungayParameter, denngayParameter, xacnhanBNParameter, dieukienParameter);
        }
    
        public virtual int NTP_BN_DIEUTRI_DSBenhNhan(Nullable<byte> mRavien, string diachi, string mThangNam, string mThamso, string hoten, string soCMT, string dVDieutri, string maBN)
        {
            var mRavienParameter = mRavien.HasValue ?
                new ObjectParameter("mRavien", mRavien) :
                new ObjectParameter("mRavien", typeof(byte));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var mThangNamParameter = mThangNam != null ?
                new ObjectParameter("mThangNam", mThangNam) :
                new ObjectParameter("mThangNam", typeof(string));
    
            var mThamsoParameter = mThamso != null ?
                new ObjectParameter("mThamso", mThamso) :
                new ObjectParameter("mThamso", typeof(string));
    
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var soCMTParameter = soCMT != null ?
                new ObjectParameter("SoCMT", soCMT) :
                new ObjectParameter("SoCMT", typeof(string));
    
            var dVDieutriParameter = dVDieutri != null ?
                new ObjectParameter("DVDieutri", dVDieutri) :
                new ObjectParameter("DVDieutri", typeof(string));
    
            var maBNParameter = maBN != null ?
                new ObjectParameter("MaBN", maBN) :
                new ObjectParameter("MaBN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_DIEUTRI_DSBenhNhan", mRavienParameter, diachiParameter, mThangNamParameter, mThamsoParameter, hotenParameter, soCMTParameter, dVDieutriParameter, maBNParameter);
        }
    
        public virtual ObjectResult<NTP_BN_DIEUTRI_SelectByDVDieutri_Result> NTP_BN_DIEUTRI_SelectByDVDieutri(Nullable<int> mID_Dieutri, string dVDieutri)
        {
            var mID_DieutriParameter = mID_Dieutri.HasValue ?
                new ObjectParameter("mID_Dieutri", mID_Dieutri) :
                new ObjectParameter("mID_Dieutri", typeof(int));
    
            var dVDieutriParameter = dVDieutri != null ?
                new ObjectParameter("DVDieutri", dVDieutri) :
                new ObjectParameter("DVDieutri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_BN_DIEUTRI_SelectByDVDieutri_Result>("NTP_BN_DIEUTRI_SelectByDVDieutri", mID_DieutriParameter, dVDieutriParameter);
        }
    
        public virtual ObjectResult<NTP_BN_DIEUTRI_SelectByIDBENHNHAN_Result> NTP_BN_DIEUTRI_SelectByIDBENHNHAN(string mID_Benhnhan, string dVDieutri)
        {
            var mID_BenhnhanParameter = mID_Benhnhan != null ?
                new ObjectParameter("mID_Benhnhan", mID_Benhnhan) :
                new ObjectParameter("mID_Benhnhan", typeof(string));
    
            var dVDieutriParameter = dVDieutri != null ?
                new ObjectParameter("DVDieutri", dVDieutri) :
                new ObjectParameter("DVDieutri", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_BN_DIEUTRI_SelectByIDBENHNHAN_Result>("NTP_BN_DIEUTRI_SelectByIDBENHNHAN", mID_BenhnhanParameter, dVDieutriParameter);
        }
    
        public virtual int NTP_BN_DIEUTRI_SelectByQuy(Nullable<byte> qUY, Nullable<int> nAM, string iD_BENHVIEN)
        {
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var iD_BENHVIENParameter = iD_BENHVIEN != null ?
                new ObjectParameter("ID_BENHVIEN", iD_BENHVIEN) :
                new ObjectParameter("ID_BENHVIEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_BN_DIEUTRI_SelectByQuy", qUYParameter, nAMParameter, iD_BENHVIENParameter);
        }
    
        public virtual ObjectResult<NTP_BN_XETNGHIEMBNTHATBAI_Result> NTP_BN_XETNGHIEMBNTHATBAI(string iD_BENHNHAN)
        {
            var iD_BENHNHANParameter = iD_BENHNHAN != null ?
                new ObjectParameter("ID_BENHNHAN", iD_BENHNHAN) :
                new ObjectParameter("ID_BENHNHAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_BN_XETNGHIEMBNTHATBAI_Result>("NTP_BN_XETNGHIEMBNTHATBAI", iD_BENHNHANParameter);
        }
    
        public virtual ObjectResult<NTP_DM_BENHVIEN_DS_BV_CHUAPHAN_DONVI_Result> NTP_DM_BENHVIEN_DS_BV_CHUAPHAN_DONVI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_DM_BENHVIEN_DS_BV_CHUAPHAN_DONVI_Result>("NTP_DM_BENHVIEN_DS_BV_CHUAPHAN_DONVI");
        }
    
        public virtual ObjectResult<NTP_DM_BENHVIEN_DS_BV_THEODONVI_Result> NTP_DM_BENHVIEN_DS_BV_THEODONVI(Nullable<int> iD_BENHVIEN)
        {
            var iD_BENHVIENParameter = iD_BENHVIEN.HasValue ?
                new ObjectParameter("ID_BENHVIEN", iD_BENHVIEN) :
                new ObjectParameter("ID_BENHVIEN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_DM_BENHVIEN_DS_BV_THEODONVI_Result>("NTP_DM_BENHVIEN_DS_BV_THEODONVI", iD_BENHVIENParameter);
        }
    
        public virtual int NTP_KD_BCHOATDONGXETNGHIEM_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, Nullable<byte> lOAIBC, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var lOAIBCParameter = lOAIBC.HasValue ?
                new ObjectParameter("LOAIBC", lOAIBC) :
                new ObjectParameter("LOAIBC", typeof(byte));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCHOATDONGXETNGHIEM_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, lOAIBCParameter, dKParameter);
        }
    
        public virtual int NTP_KD_BCHOATDONGXETNGHIEMBYHUYEN_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, Nullable<byte> lOAIBC, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var lOAIBCParameter = lOAIBC.HasValue ?
                new ObjectParameter("LOAIBC", lOAIBC) :
                new ObjectParameter("LOAIBC", typeof(byte));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCHOATDONGXETNGHIEMBYHUYEN_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, lOAIBCParameter, dKParameter);
        }
    
        public virtual int NTP_KD_BCHOATDONGXN_TUYENHUYEN(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, Nullable<int> nAM, Nullable<byte> qUY, string dVBAOCAO, Nullable<byte> cAPNHATDL)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            var cAPNHATDLParameter = cAPNHATDL.HasValue ?
                new ObjectParameter("CAPNHATDL", cAPNHATDL) :
                new ObjectParameter("CAPNHATDL", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCHOATDONGXN_TUYENHUYEN", tUNGAYParameter, dENNGAYParameter, nAMParameter, qUYParameter, dVBAOCAOParameter, cAPNHATDLParameter);
        }
    
        public virtual int NTP_KD_BCHOATDONGXN_TUYENHUYEN_TEST(Nullable<System.DateTime> tUNGAY, Nullable<System.DateTime> dENNGAY, Nullable<int> nAM, Nullable<byte> qUY, string dVBAOCAO, Nullable<byte> cAPNHATDL)
        {
            var tUNGAYParameter = tUNGAY.HasValue ?
                new ObjectParameter("TUNGAY", tUNGAY) :
                new ObjectParameter("TUNGAY", typeof(System.DateTime));
    
            var dENNGAYParameter = dENNGAY.HasValue ?
                new ObjectParameter("DENNGAY", dENNGAY) :
                new ObjectParameter("DENNGAY", typeof(System.DateTime));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            var cAPNHATDLParameter = cAPNHATDL.HasValue ?
                new ObjectParameter("CAPNHATDL", cAPNHATDL) :
                new ObjectParameter("CAPNHATDL", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCHOATDONGXN_TUYENHUYEN_TEST", tUNGAYParameter, dENNGAYParameter, nAMParameter, qUYParameter, dVBAOCAOParameter, cAPNHATDLParameter);
        }
    
        public virtual int NTP_KD_BCKETQUAKD_TUYENHUYEN(Nullable<byte> qUY, Nullable<int> nAM, string iD_BENHVIEN)
        {
            var qUYParameter = qUY.HasValue ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var iD_BENHVIENParameter = iD_BENHVIEN != null ?
                new ObjectParameter("ID_BENHVIEN", iD_BENHVIEN) :
                new ObjectParameter("ID_BENHVIEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCKETQUAKD_TUYENHUYEN", qUYParameter, nAMParameter, iD_BENHVIENParameter);
        }
    
        public virtual int NTP_KD_BCKETQUAKD_TUYENTINH(string mATINH, Nullable<int> nAM, string qUY, string dVBAOCAO)
        {
            var mATINHParameter = mATINH != null ?
                new ObjectParameter("MATINH", mATINH) :
                new ObjectParameter("MATINH", typeof(string));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCKETQUAKD_TUYENTINH", mATINHParameter, nAMParameter, qUYParameter, dVBAOCAOParameter);
        }
    
        public virtual int NTP_KD_BCKIEMDINHTB_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, Nullable<byte> lOAIBC, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var lOAIBCParameter = lOAIBC.HasValue ?
                new ObjectParameter("LOAIBC", lOAIBC) :
                new ObjectParameter("LOAIBC", typeof(byte));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCKIEMDINHTB_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, lOAIBCParameter, dKParameter);
        }
    
        public virtual int NTP_KD_BCTHUDOMPHBYHUYEN_IN(string tINH, Nullable<byte> mIEN, Nullable<byte> vUNG, Nullable<int> nAM, string qUY, string dK)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var mIENParameter = mIEN.HasValue ?
                new ObjectParameter("MIEN", mIEN) :
                new ObjectParameter("MIEN", typeof(byte));
    
            var vUNGParameter = vUNG.HasValue ?
                new ObjectParameter("VUNG", vUNG) :
                new ObjectParameter("VUNG", typeof(byte));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var dKParameter = dK != null ?
                new ObjectParameter("DK", dK) :
                new ObjectParameter("DK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCTHUDOMPHBYHUYEN_IN", tINHParameter, mIENParameter, vUNGParameter, nAMParameter, qUYParameter, dKParameter);
        }
    
        public virtual int NTP_KD_BCTONGHOPTUYENTINH_IN(string tINH, Nullable<int> nAM, string qUY, Nullable<byte> phanloaiBC, string dVBAOCAO)
        {
            var tINHParameter = tINH != null ?
                new ObjectParameter("TINH", tINH) :
                new ObjectParameter("TINH", typeof(string));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var qUYParameter = qUY != null ?
                new ObjectParameter("QUY", qUY) :
                new ObjectParameter("QUY", typeof(string));
    
            var phanloaiBCParameter = phanloaiBC.HasValue ?
                new ObjectParameter("phanloaiBC", phanloaiBC) :
                new ObjectParameter("phanloaiBC", typeof(byte));
    
            var dVBAOCAOParameter = dVBAOCAO != null ?
                new ObjectParameter("DVBAOCAO", dVBAOCAO) :
                new ObjectParameter("DVBAOCAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_KD_BCTONGHOPTUYENTINH_IN", tINHParameter, nAMParameter, qUYParameter, phanloaiBCParameter, dVBAOCAOParameter);
        }
    
        public virtual ObjectResult<NTP_QLT_BAOCAO_TONGHOP_KIEMKE_Result> NTP_QLT_BAOCAO_TONGHOP_KIEMKE(Nullable<int> iD_Kho, Nullable<int> iD_Ky_KiemKe)
        {
            var iD_KhoParameter = iD_Kho.HasValue ?
                new ObjectParameter("ID_Kho", iD_Kho) :
                new ObjectParameter("ID_Kho", typeof(int));
    
            var iD_Ky_KiemKeParameter = iD_Ky_KiemKe.HasValue ?
                new ObjectParameter("ID_Ky_KiemKe", iD_Ky_KiemKe) :
                new ObjectParameter("ID_Ky_KiemKe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLT_BAOCAO_TONGHOP_KIEMKE_Result>("NTP_QLT_BAOCAO_TONGHOP_KIEMKE", iD_KhoParameter, iD_Ky_KiemKeParameter);
        }
    
        public virtual ObjectResult<NTP_QLT_BAOCAO_TONGHOP_NHAPXUAT_Result> NTP_QLT_BAOCAO_TONGHOP_NHAPXUAT(Nullable<int> thang, Nullable<int> nam, Nullable<int> iD_Kho)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            var iD_KhoParameter = iD_Kho.HasValue ?
                new ObjectParameter("ID_Kho", iD_Kho) :
                new ObjectParameter("ID_Kho", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLT_BAOCAO_TONGHOP_NHAPXUAT_Result>("NTP_QLT_BAOCAO_TONGHOP_NHAPXUAT", thangParameter, namParameter, iD_KhoParameter);
        }
    
        public virtual ObjectResult<NTP_QLT_BC_SUDUNGTHUOC_Result> NTP_QLT_BC_SUDUNGTHUOC(Nullable<long> id_kho, Nullable<long> id_baocao, Nullable<int> type)
        {
            var id_khoParameter = id_kho.HasValue ?
                new ObjectParameter("id_kho", id_kho) :
                new ObjectParameter("id_kho", typeof(long));
    
            var id_baocaoParameter = id_baocao.HasValue ?
                new ObjectParameter("id_baocao", id_baocao) :
                new ObjectParameter("id_baocao", typeof(long));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLT_BC_SUDUNGTHUOC_Result>("NTP_QLT_BC_SUDUNGTHUOC", id_khoParameter, id_baocaoParameter, typeParameter);
        }
    
        public virtual int NTP_QLT_BC_SUDUNGTHUOC_HUYPHEDUYET(Nullable<long> id_kho, Nullable<long> iD_BAOCAO, Nullable<int> nGUOI_PHEDUYET)
        {
            var id_khoParameter = id_kho.HasValue ?
                new ObjectParameter("id_kho", id_kho) :
                new ObjectParameter("id_kho", typeof(long));
    
            var iD_BAOCAOParameter = iD_BAOCAO.HasValue ?
                new ObjectParameter("ID_BAOCAO", iD_BAOCAO) :
                new ObjectParameter("ID_BAOCAO", typeof(long));
    
            var nGUOI_PHEDUYETParameter = nGUOI_PHEDUYET.HasValue ?
                new ObjectParameter("NGUOI_PHEDUYET", nGUOI_PHEDUYET) :
                new ObjectParameter("NGUOI_PHEDUYET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLT_BC_SUDUNGTHUOC_HUYPHEDUYET", id_khoParameter, iD_BAOCAOParameter, nGUOI_PHEDUYETParameter);
        }
    
        public virtual int NTP_QLT_BC_SUDUNGTHUOC_PHEDUYET(Nullable<long> id_kho, Nullable<long> iD_BAOCAO, Nullable<int> nGUOI_PHEDUYET)
        {
            var id_khoParameter = id_kho.HasValue ?
                new ObjectParameter("id_kho", id_kho) :
                new ObjectParameter("id_kho", typeof(long));
    
            var iD_BAOCAOParameter = iD_BAOCAO.HasValue ?
                new ObjectParameter("ID_BAOCAO", iD_BAOCAO) :
                new ObjectParameter("ID_BAOCAO", typeof(long));
    
            var nGUOI_PHEDUYETParameter = nGUOI_PHEDUYET.HasValue ?
                new ObjectParameter("NGUOI_PHEDUYET", nGUOI_PHEDUYET) :
                new ObjectParameter("NGUOI_PHEDUYET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLT_BC_SUDUNGTHUOC_PHEDUYET", id_khoParameter, iD_BAOCAOParameter, nGUOI_PHEDUYETParameter);
        }
    
        public virtual ObjectResult<NTP_QLT_BC_SUDUNGTHUOC_TW_Result> NTP_QLT_BC_SUDUNGTHUOC_TW(Nullable<long> id_kho, Nullable<int> quy, Nullable<int> nam)
        {
            var id_khoParameter = id_kho.HasValue ?
                new ObjectParameter("id_kho", id_kho) :
                new ObjectParameter("id_kho", typeof(long));
    
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLT_BC_SUDUNGTHUOC_TW_Result>("NTP_QLT_BC_SUDUNGTHUOC_TW", id_khoParameter, quyParameter, namParameter);
        }
    
        public virtual int NTP_QLTTB_KETCHUYENSOLIEU(Nullable<long> iD_KHO, Nullable<long> iD_KY_KIEMKE, Nullable<int> nGUOI_NM)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(long));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            var nGUOI_NMParameter = nGUOI_NM.HasValue ?
                new ObjectParameter("NGUOI_NM", nGUOI_NM) :
                new ObjectParameter("NGUOI_NM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLTTB_KETCHUYENSOLIEU", iD_KHOParameter, iD_KY_KIEMKEParameter, nGUOI_NMParameter);
        }
    
        public virtual int NTP_QLTTB_KHOASO(Nullable<int> nAM, Nullable<long> iD_KHO, string tEN_KY_KIEMKE, Nullable<int> nGUOI_NM, Nullable<System.DateTime> nGAY_KIEMKE)
        {
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(long));
    
            var tEN_KY_KIEMKEParameter = tEN_KY_KIEMKE != null ?
                new ObjectParameter("TEN_KY_KIEMKE", tEN_KY_KIEMKE) :
                new ObjectParameter("TEN_KY_KIEMKE", typeof(string));
    
            var nGUOI_NMParameter = nGUOI_NM.HasValue ?
                new ObjectParameter("NGUOI_NM", nGUOI_NM) :
                new ObjectParameter("NGUOI_NM", typeof(int));
    
            var nGAY_KIEMKEParameter = nGAY_KIEMKE.HasValue ?
                new ObjectParameter("NGAY_KIEMKE", nGAY_KIEMKE) :
                new ObjectParameter("NGAY_KIEMKE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLTTB_KHOASO", nAMParameter, iD_KHOParameter, tEN_KY_KIEMKEParameter, nGUOI_NMParameter, nGAY_KIEMKEParameter);
        }
    
        public virtual ObjectResult<NTP_QLTTB_KHOASO_SEARCH_Result> NTP_QLTTB_KHOASO_SEARCH(Nullable<long> iD_KHO, Nullable<int> yEAR)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(long));
    
            var yEARParameter = yEAR.HasValue ?
                new ObjectParameter("YEAR", yEAR) :
                new ObjectParameter("YEAR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLTTB_KHOASO_SEARCH_Result>("NTP_QLTTB_KHOASO_SEARCH", iD_KHOParameter, yEARParameter);
        }
    
        public virtual ObjectResult<NTP_QLTTB_PHIEUXUAT_SelectByMa_Result> NTP_QLTTB_PHIEUXUAT_SelectByMa(string mA_PHIEUXUAT)
        {
            var mA_PHIEUXUATParameter = mA_PHIEUXUAT != null ?
                new ObjectParameter("MA_PHIEUXUAT", mA_PHIEUXUAT) :
                new ObjectParameter("MA_PHIEUXUAT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLTTB_PHIEUXUAT_SelectByMa_Result>("NTP_QLTTB_PHIEUXUAT_SelectByMa", mA_PHIEUXUATParameter);
        }
    
        public virtual ObjectResult<NTP_QLTTB_SoTheoDoiTTB_Result> NTP_QLTTB_SoTheoDoiTTB(Nullable<long> id_Kho, Nullable<long> id_ThietBi)
        {
            var id_KhoParameter = id_Kho.HasValue ?
                new ObjectParameter("Id_Kho", id_Kho) :
                new ObjectParameter("Id_Kho", typeof(long));
    
            var id_ThietBiParameter = id_ThietBi.HasValue ?
                new ObjectParameter("Id_ThietBi", id_ThietBi) :
                new ObjectParameter("Id_ThietBi", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLTTB_SoTheoDoiTTB_Result>("NTP_QLTTB_SoTheoDoiTTB", id_KhoParameter, id_ThietBiParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_BAOCAO_HOACHAT_TUYENTINH_Result> NTP_QLVT_BAOCAO_HOACHAT_TUYENTINH(Nullable<int> iD_KHO, Nullable<long> iD_KY_KIEMKE)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_BAOCAO_HOACHAT_TUYENTINH_Result>("NTP_QLVT_BAOCAO_HOACHAT_TUYENTINH", iD_KHOParameter, iD_KY_KIEMKEParameter);
        }
    
        public virtual int NTP_QLVT_BAOCAO_TONGHOP_KIEMKE(Nullable<int> iD_KHO, Nullable<long> iD_KY_KIEMKE)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLVT_BAOCAO_TONGHOP_KIEMKE", iD_KHOParameter, iD_KY_KIEMKEParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_BAOCAO_VATTU_HOACHAT_MAIN_TUYENTINH_Result> NTP_QLVT_BAOCAO_VATTU_HOACHAT_MAIN_TUYENTINH(Nullable<int> iD_KHO, Nullable<long> iD_KY_KIEMKE)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_BAOCAO_VATTU_HOACHAT_MAIN_TUYENTINH_Result>("NTP_QLVT_BAOCAO_VATTU_HOACHAT_MAIN_TUYENTINH", iD_KHOParameter, iD_KY_KIEMKEParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_BAOCAO_VATTU_TUYENHUYEN_Result> NTP_QLVT_BAOCAO_VATTU_TUYENHUYEN(Nullable<int> iD_KHO, Nullable<long> iD_KY_KIEMKE)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_BAOCAO_VATTU_TUYENHUYEN_Result>("NTP_QLVT_BAOCAO_VATTU_TUYENHUYEN", iD_KHOParameter, iD_KY_KIEMKEParameter);
        }
    
        public virtual int NTP_QLVT_BAOCAO_VATTU_TUYENTINH(Nullable<int> iD_KHO, Nullable<long> iD_KY_KIEMKE)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLVT_BAOCAO_VATTU_TUYENTINH", iD_KHOParameter, iD_KY_KIEMKEParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_GET_LASTEST_KY_KIEMKE_Result> NTP_QLVT_GET_LASTEST_KY_KIEMKE(Nullable<int> iD_KHO)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_GET_LASTEST_KY_KIEMKE_Result>("NTP_QLVT_GET_LASTEST_KY_KIEMKE", iD_KHOParameter);
        }
    
        public virtual int NTP_QLVT_KETCHUYEN_SOLIEU(Nullable<int> iD_KHO, Nullable<long> iD_KY_KIEMKE, Nullable<int> nGUOI_NM)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var iD_KY_KIEMKEParameter = iD_KY_KIEMKE.HasValue ?
                new ObjectParameter("ID_KY_KIEMKE", iD_KY_KIEMKE) :
                new ObjectParameter("ID_KY_KIEMKE", typeof(long));
    
            var nGUOI_NMParameter = nGUOI_NM.HasValue ?
                new ObjectParameter("NGUOI_NM", nGUOI_NM) :
                new ObjectParameter("NGUOI_NM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLVT_KETCHUYEN_SOLIEU", iD_KHOParameter, iD_KY_KIEMKEParameter, nGUOI_NMParameter);
        }
    
        public virtual int NTP_QLVT_KHOASO_KIEMKE(Nullable<long> iD_KHO_QLVT, Nullable<int> tHANG, Nullable<int> nAM, string mO_TA, Nullable<int> nGUOI_NM, Nullable<int> lAN_KIEMKE)
        {
            var iD_KHO_QLVTParameter = iD_KHO_QLVT.HasValue ?
                new ObjectParameter("ID_KHO_QLVT", iD_KHO_QLVT) :
                new ObjectParameter("ID_KHO_QLVT", typeof(long));
    
            var tHANGParameter = tHANG.HasValue ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            var mO_TAParameter = mO_TA != null ?
                new ObjectParameter("MO_TA", mO_TA) :
                new ObjectParameter("MO_TA", typeof(string));
    
            var nGUOI_NMParameter = nGUOI_NM.HasValue ?
                new ObjectParameter("NGUOI_NM", nGUOI_NM) :
                new ObjectParameter("NGUOI_NM", typeof(int));
    
            var lAN_KIEMKEParameter = lAN_KIEMKE.HasValue ?
                new ObjectParameter("LAN_KIEMKE", lAN_KIEMKE) :
                new ObjectParameter("LAN_KIEMKE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NTP_QLVT_KHOASO_KIEMKE", iD_KHO_QLVTParameter, tHANGParameter, nAMParameter, mO_TAParameter, nGUOI_NMParameter, lAN_KIEMKEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> NTP_QLVT_KIEMTRA_KY(Nullable<long> iD_KHO, Nullable<int> tHANG, Nullable<int> nAM)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(long));
    
            var tHANGParameter = tHANG.HasValue ?
                new ObjectParameter("THANG", tHANG) :
                new ObjectParameter("THANG", typeof(int));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("NTP_QLVT_KIEMTRA_KY", iD_KHOParameter, tHANGParameter, nAMParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_KY_KIEMKE_SEARCH_Result> NTP_QLVT_KY_KIEMKE_SEARCH(Nullable<long> iD_KHO, Nullable<int> nAM)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(long));
    
            var nAMParameter = nAM.HasValue ?
                new ObjectParameter("NAM", nAM) :
                new ObjectParameter("NAM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_KY_KIEMKE_SEARCH_Result>("NTP_QLVT_KY_KIEMKE_SEARCH", iD_KHOParameter, nAMParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_SO_HOACHAT_Result> NTP_QLVT_SO_HOACHAT(Nullable<int> iD_KHO, Nullable<System.DateTime> dATEFROM, Nullable<System.DateTime> dATETO, Nullable<long> iD_VATTU)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var dATEFROMParameter = dATEFROM.HasValue ?
                new ObjectParameter("DATEFROM", dATEFROM) :
                new ObjectParameter("DATEFROM", typeof(System.DateTime));
    
            var dATETOParameter = dATETO.HasValue ?
                new ObjectParameter("DATETO", dATETO) :
                new ObjectParameter("DATETO", typeof(System.DateTime));
    
            var iD_VATTUParameter = iD_VATTU.HasValue ?
                new ObjectParameter("ID_VATTU", iD_VATTU) :
                new ObjectParameter("ID_VATTU", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_SO_HOACHAT_Result>("NTP_QLVT_SO_HOACHAT", iD_KHOParameter, dATEFROMParameter, dATETOParameter, iD_VATTUParameter);
        }
    
        public virtual ObjectResult<NTP_QLVT_SO_VATTU_Result> NTP_QLVT_SO_VATTU(Nullable<int> iD_KHO, Nullable<System.DateTime> dATEFROM, Nullable<System.DateTime> dATETO, Nullable<long> iD_VATTU)
        {
            var iD_KHOParameter = iD_KHO.HasValue ?
                new ObjectParameter("ID_KHO", iD_KHO) :
                new ObjectParameter("ID_KHO", typeof(int));
    
            var dATEFROMParameter = dATEFROM.HasValue ?
                new ObjectParameter("DATEFROM", dATEFROM) :
                new ObjectParameter("DATEFROM", typeof(System.DateTime));
    
            var dATETOParameter = dATETO.HasValue ?
                new ObjectParameter("DATETO", dATETO) :
                new ObjectParameter("DATETO", typeof(System.DateTime));
    
            var iD_VATTUParameter = iD_VATTU.HasValue ?
                new ObjectParameter("ID_VATTU", iD_VATTU) :
                new ObjectParameter("ID_VATTU", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NTP_QLVT_SO_VATTU_Result>("NTP_QLVT_SO_VATTU", iD_KHOParameter, dATEFROMParameter, dATETOParameter, iD_VATTUParameter);
        }
    }
}
