//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_KD_BC_HOATDONGXNC
    {
        public decimal ID_HOATDONGXNC { get; set; }
        public Nullable<decimal> ID_HOATDONGXN { get; set; }
        public byte PHANLOAI { get; set; }
        public Nullable<int> DuongAFB1Mau { get; set; }
        public Nullable<int> DuongAFB2Mau { get; set; }
        public Nullable<int> DuongAFB3Mau { get; set; }
        public Nullable<int> AmAFB1Mau { get; set; }
        public Nullable<int> AmAFB2Mau { get; set; }
        public Nullable<int> AmAFB3Mau { get; set; }
        public Nullable<int> SoBNDangky { get; set; }
        public Nullable<int> ID_HOATDONGXNP1 { get; set; }
        public Nullable<int> AmAFB2Mau1 { get; set; }
        public Nullable<int> AmAFB1Mau1 { get; set; }
        public Nullable<int> AmAFB3Mau1 { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
