//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_KHO
    {
        public long ID_KY_KIEMKE { get; set; }
        public long ID_KHO { get; set; }
        public int ID_VATTU { get; set; }
        public decimal TON_DAU { get; set; }
        public decimal NHAP { get; set; }
        public decimal XUAT { get; set; }
        public decimal TON_CUOI { get; set; }
        public int NGUOI_NM { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public decimal THUA { get; set; }
        public decimal THIEU { get; set; }
        public decimal HONG { get; set; }
        public string LO_SANXUAT { get; set; }
        public decimal TOT { get; set; }
        public Nullable<System.DateTime> HAN_SUDUNG { get; set; }
        public int LAN_KIEMKE { get; set; }
        public int NAM { get; set; }
    
        public virtual NTP_QLVT_DM_KHO NTP_QLVT_DM_KHO { get; set; }
        public virtual NTP_QLVT_DM_VATTU NTP_QLVT_DM_VATTU { get; set; }
        public virtual NTP_QLVT_KY_KIEMKE NTP_QLVT_KY_KIEMKE { get; set; }
    }
}
