//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLTTB_KY_KIEMKE
    {
        public NTP_QLTTB_KY_KIEMKE()
        {
            this.NTP_QLTTB_KIEMKE = new HashSet<NTP_QLTTB_KIEMKE>();
            this.NTP_QLTTB_KHO = new HashSet<NTP_QLTTB_KHO>();
            this.NTP_QLTTB_KY_KIEMKE_CHITIET = new HashSet<NTP_QLTTB_KY_KIEMKE_CHITIET>();
        }
    
        public long ID_KY_KIEMKE { get; set; }
        public long ID_KHO { get; set; }
        public System.DateTime NGAY_KIEMKE { get; set; }
        public int TRANG_THAI { get; set; }
        public string TEN_KY_KIEMKE { get; set; }
        public int NGUOI_NM { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NAM { get; set; }
    
        public virtual ICollection<NTP_QLTTB_KIEMKE> NTP_QLTTB_KIEMKE { get; set; }
        public virtual ICollection<NTP_QLTTB_KHO> NTP_QLTTB_KHO { get; set; }
        public virtual ICollection<NTP_QLTTB_KY_KIEMKE_CHITIET> NTP_QLTTB_KY_KIEMKE_CHITIET { get; set; }
    }
}
