//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_TTB_TH_KHO
    {
        public decimal ID_BC_NX_DETAIL { get; set; }
        public long ID_KHO { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
        public long ID_THIETBI { get; set; }
        public int ID_NGUONKINHPHI { get; set; }
        public decimal TON_DAU { get; set; }
        public decimal NHAP { get; set; }
        public decimal XUAT_SUDUNG { get; set; }
        public decimal TON_CUOI { get; set; }
        public decimal TRA_LAI { get; set; }
        public decimal THUA { get; set; }
        public decimal HONG_VO { get; set; }
        public decimal THIEU { get; set; }
        public decimal DIEU_CHUYEN { get; set; }
        public Nullable<System.DateTime> NGAY_KHOA_SO { get; set; }
        public int TRANG_THAI { get; set; }
        public decimal XUAT_DONVI { get; set; }
    }
}
