//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_PHANHOI
    {
        public int ID_Phanhoi { get; set; }
        public Nullable<int> ID_Dieutri { get; set; }
        public Nullable<bool> Phanloai { get; set; }
        public Nullable<long> DVChuyen { get; set; }
        public Nullable<System.DateTime> NgayTN { get; set; }
        public Nullable<long> DVTiepNhan { get; set; }
        public Nullable<System.DateTime> NgayKTDT { get; set; }
        public string SoDKDT { get; set; }
        public Nullable<int> ID_KetquaDT { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NGUOI_NM { get; set; }
    }
}
