//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_VATTUHOACHAT_VT
    {
        public decimal ID_CHITIET { get; set; }
        public decimal ID_BAOCAO { get; set; }
        public long ID_VATTU { get; set; }
        public decimal TD_TINH { get; set; }
        public decimal TD_BVHUYENTINH { get; set; }
        public decimal N_TW_CAP { get; set; }
        public decimal N_TINH_CAP { get; set; }
        public decimal X_TOANTINH { get; set; }
        public decimal X_SUDUNG { get; set; }
        public decimal THUA_TINH { get; set; }
        public decimal THUA_HUYEN { get; set; }
        public decimal THIEU_TINH { get; set; }
        public decimal THIEU_HUYEN { get; set; }
        public decimal TC_TINH { get; set; }
        public decimal TC_HUYEN { get; set; }
        public Nullable<int> ID_NGUONKINHPHI { get; set; }
        public Nullable<int> ID_DONVI { get; set; }
        public Nullable<decimal> TRA_LAI { get; set; }
        public Nullable<decimal> HONG_TINH { get; set; }
        public Nullable<decimal> DIEU_CHUYEN { get; set; }
    }
}
