//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_KIEMKE
    {
        public NTP_QLVT_KIEMKE()
        {
            this.NTP_QLVT_KIEMKE_CHITIET = new HashSet<NTP_QLVT_KIEMKE_CHITIET>();
        }
    
        public decimal ID_KIEMKE { get; set; }
        public long ID_KHO { get; set; }
        public System.DateTime NGAY_KIEMKE { get; set; }
        public int NGUOI_KIEMKE { get; set; }
        public long ID_KY_KIEMKE { get; set; }
        public string GHI_CHU { get; set; }
        public int ID_NGUONKINHPHI { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int TRANG_THAI { get; set; }
    
        public virtual ICollection<NTP_QLVT_KIEMKE_CHITIET> NTP_QLVT_KIEMKE_CHITIET { get; set; }
        public virtual NTP_QLVT_KY_KIEMKE NTP_QLVT_KY_KIEMKE { get; set; }
    }
}
