//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLT_KY_KIEMKE_CHITIET
    {
        public decimal ID_KY_KIEMKE_CHITIET { get; set; }
        public long ID_KY_KIEMKE { get; set; }
        public long ID_THUOC { get; set; }
        public string LO_SX { get; set; }
        public string HAN_SUDUNG { get; set; }
        public decimal TONG_XUAT { get; set; }
        public decimal TONG_NHAP { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
    }
}
