//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLT_PHIEUNHAP_CHITIET
    {
        public decimal ID_PHIEUNHAP_CHITIET { get; set; }
        public decimal ID_PHIEUNHAP { get; set; }
        public int ID_THUOC { get; set; }
        public string LO_SX { get; set; }
        public System.DateTime HAN_SUDUNG { get; set; }
        public Nullable<System.DateTime> NGAY_SX { get; set; }
        public decimal SO_LUONG { get; set; }
    
        public virtual NTP_QLT_PHIEUNHAP NTP_QLT_PHIEUNHAP { get; set; }
    }
}
