//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_SURVEY_OPTION
    {
        public NTP_SURVEY_OPTION()
        {
            this.NTP_SURVEY_RESULT = new HashSet<NTP_SURVEY_RESULT>();
        }
    
        public decimal SURVEY_OPTION_ID { get; set; }
        public decimal SURVEY_ID { get; set; }
        public decimal QUESTION_ID { get; set; }
        public int VIEW_ORDER { get; set; }
        public string OPTION_NAME { get; set; }
        public int IS_CORRECT { get; set; }
    
        public virtual NTP_SURVEY_QUESTION NTP_SURVEY_QUESTION { get; set; }
        public virtual NTP_SURVEYS NTP_SURVEYS { get; set; }
        public virtual ICollection<NTP_SURVEY_RESULT> NTP_SURVEY_RESULT { get; set; }
    }
}
