//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_KY_KIEMKE_CHITIET
    {
        public decimal ID_KY_KIEMKE_CHITIET { get; set; }
        public long ID_KHO { get; set; }
        public long ID_KY_KIEMKE { get; set; }
        public int ID_VATTU { get; set; }
        public string LO_SANXUAT { get; set; }
        public decimal TONG_XUAT { get; set; }
        public decimal TONG_NHAP { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
        public decimal TON_DAU { get; set; }
    
        public virtual NTP_QLVT_DM_KHO NTP_QLVT_DM_KHO { get; set; }
        public virtual NTP_QLVT_DM_VATTU NTP_QLVT_DM_VATTU { get; set; }
        public virtual NTP_QLVT_KY_KIEMKE NTP_QLVT_KY_KIEMKE { get; set; }
    }
}
