//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_BC_THUNHANBNLAOP1
    {
        public int ID_BCThunhanBNLaoP1 { get; set; }
        public int ID_BCThunhanBNLao { get; set; }
        public long Phanloai { get; set; }
        public Nullable<int> Moi { get; set; }
        public Nullable<int> Taiphat { get; set; }
        public Nullable<int> Thatbai { get; set; }
        public Nullable<int> Taitri { get; set; }
        public Nullable<int> AFBKhac { get; set; }
        public Nullable<int> AmNho { get; set; }
        public Nullable<int> AmTrung { get; set; }
        public Nullable<int> AmLon { get; set; }
        public Nullable<int> NgoaiPhoiNho { get; set; }
        public Nullable<int> NgoaiPhoiTrung { get; set; }
        public Nullable<int> NgoaiPhoiLon { get; set; }
        public Nullable<int> NgoaiphoiKhac { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
