//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_DM_MIEN
    {
        public NTP_DM_MIEN()
        {
            this.NTP_QLTTB_DM_KHO = new HashSet<NTP_QLTTB_DM_KHO>();
        }
    
        public int ID_MIEN { get; set; }
        public string TEN_MIEN { get; set; }
    
        public virtual ICollection<NTP_QLTTB_DM_KHO> NTP_QLTTB_DM_KHO { get; set; }
    }
}
