//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_TINHHINHTRIENKHAICTCL
    {
        public int ID_TRIENKHAI { get; set; }
        public int Nam { get; set; }
        public string Ma_TINH { get; set; }
        public Nullable<int> SLHuyen { get; set; }
        public Nullable<int> SLHuyenTK { get; set; }
        public Nullable<int> SLXa { get; set; }
        public Nullable<int> SLXaTK { get; set; }
        public Nullable<int> DansoTinh { get; set; }
        public Nullable<int> SodanTK { get; set; }
        public Nullable<int> SoDVQL { get; set; }
    }
}
