//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLTTB_KIEMKE_CHITIET
    {
        public decimal ID_KIEMKE_CHITIET { get; set; }
        public decimal ID_KIEMKE { get; set; }
        public int ID_THIETBI { get; set; }
        public int ID_TRANGTHAI { get; set; }
        public decimal SO_LUONG { get; set; }
    
        public virtual NTP_QLTTB_DM_TRANGTHAI NTP_QLTTB_DM_TRANGTHAI { get; set; }
        public virtual NTP_QLTTB_KIEMKE NTP_QLTTB_KIEMKE { get; set; }
    }
}
