//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_VATTUHOACHAT_HC
    {
        public decimal ID_CHITIET { get; set; }
        public long ID_BAOCAO { get; set; }
        public long ID_VATTU { get; set; }
        public decimal TON_DAU { get; set; }
        public decimal NHAP { get; set; }
        public decimal XUAT { get; set; }
        public decimal THUA { get; set; }
        public decimal THIEU_HONG { get; set; }
        public decimal TON_CUOI { get; set; }
        public Nullable<System.DateTime> HAN_SUDUNG { get; set; }
        public int NGUOI_NM { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<int> ID_NGUONKINHPHI { get; set; }
        public string LO_SX { get; set; }
    }
}
