//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLT_KHOTHUOC
    {
        public long ID_KHO { get; set; }
        public long ID_KY_KIEMKE { get; set; }
        public long ID_THUOC { get; set; }
        public decimal TON_DAUKY { get; set; }
        public decimal NHAP { get; set; }
        public decimal XUAT { get; set; }
        public decimal TON_CUOIKY { get; set; }
        public decimal THUA { get; set; }
        public decimal THIEU { get; set; }
        public decimal HONG { get; set; }
        public string LO_SX { get; set; }
        public Nullable<decimal> TOT { get; set; }
        public Nullable<decimal> KEM_PC { get; set; }
        public Nullable<decimal> MAT_PC { get; set; }
    
        public virtual NTP_DM_THUOC NTP_DM_THUOC { get; set; }
        public virtual NTP_QLT_DM_KHOTHUOC NTP_QLT_DM_KHOTHUOC { get; set; }
        public virtual NTP_QLT_KY_KIEMKE NTP_QLT_KY_KIEMKE { get; set; }
    }
}
