//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_KY_KIEMKE
    {
        public NTP_QLVT_KY_KIEMKE()
        {
            this.NTP_QLVT_KIEMKE = new HashSet<NTP_QLVT_KIEMKE>();
            this.NTP_QLVT_KHO = new HashSet<NTP_QLVT_KHO>();
            this.NTP_QLVT_KY_KIEMKE_CHITIET = new HashSet<NTP_QLVT_KY_KIEMKE_CHITIET>();
        }
    
        public long ID_KY_KIEMKE { get; set; }
        public long ID_KHO { get; set; }
        public System.DateTime NGAY_BATDAU { get; set; }
        public System.DateTime NGAY_KETTHUC { get; set; }
        public int TRANG_THAI { get; set; }
        public int NAM { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public string TEN_KY_KIEMKE { get; set; }
        public int LAN_KIEMKE { get; set; }
    
        public virtual ICollection<NTP_QLVT_KIEMKE> NTP_QLVT_KIEMKE { get; set; }
        public virtual ICollection<NTP_QLVT_KHO> NTP_QLVT_KHO { get; set; }
        public virtual ICollection<NTP_QLVT_KY_KIEMKE_CHITIET> NTP_QLVT_KY_KIEMKE_CHITIET { get; set; }
    }
}
