//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_VT_TH_NHAPXUAT
    {
        public decimal ID_BAOCAO_NX { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
        public long ID_KHO { get; set; }
        public System.DateTime NGAY_TAO { get; set; }
        public int NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_KHOASO { get; set; }
        public Nullable<int> NGUOI_KHOASO { get; set; }
        public int TRANG_THAI { get; set; }
    }
}
