//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_CU_HC_IMPORT
    {
        public decimal ID_IMPORT { get; set; }
        public decimal ID_KHO { get; set; }
        public int ID_VATTU { get; set; }
        public int ID_NGUONKINHPHI { get; set; }
        public System.DateTime NGAY_NHAP_KHO { get; set; }
        public string LO_SX { get; set; }
        public System.DateTime HAN_DUNG { get; set; }
        public decimal SO_LUONG { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NGUOI_NM { get; set; }
        public int TRANG_THAI { get; set; }
        public string MA_PHIEU { get; set; }
        public string NGUOI_VIETPHIEU { get; set; }
        public Nullable<System.DateTime> NGAY_SX { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> LOAI_NHAP { get; set; }
    }
}
