//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLT_KIEMKE_CHITIET
    {
        public decimal ID_KIEMKE_CHITIET { get; set; }
        public decimal ID_KIEMKE { get; set; }
        public long ID_THUOC { get; set; }
        public int ID_TRANGTHAI { get; set; }
        public string LO_SX { get; set; }
        public Nullable<System.DateTime> HAN_SUDUNG { get; set; }
        public Nullable<System.DateTime> NGAY_SX { get; set; }
        public decimal SO_LUONG { get; set; }
        public int LOAI_PHIEU { get; set; }
    
        public virtual NTP_DM_THUOC NTP_DM_THUOC { get; set; }
        public virtual NTP_QLT_DM_TRANGTHAI NTP_QLT_DM_TRANGTHAI { get; set; }
        public virtual NTP_QLT_KIEMKE NTP_QLT_KIEMKE { get; set; }
    }
}
