//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_BCTHUNHAN
    {
        public Nullable<int> id_PL { get; set; }
        public string TenPL { get; set; }
        public string id_benhvien { get; set; }
        public Nullable<int> NAM0 { get; set; }
        public Nullable<int> NU0 { get; set; }
        public Nullable<int> NAM5 { get; set; }
        public Nullable<int> NU5 { get; set; }
        public Nullable<int> NAM15 { get; set; }
        public Nullable<int> NU15 { get; set; }
        public Nullable<int> NAM25 { get; set; }
        public Nullable<int> NU25 { get; set; }
        public Nullable<int> NAM35 { get; set; }
        public Nullable<int> NU35 { get; set; }
        public Nullable<int> NAM45 { get; set; }
        public Nullable<int> NU45 { get; set; }
        public Nullable<int> NAM55 { get; set; }
        public Nullable<int> NU55 { get; set; }
        public Nullable<int> NAM65 { get; set; }
        public Nullable<int> NU65 { get; set; }
    }
}
