//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_KD_PLAYMAU_C
    {
        public decimal ID_PLAYMAU_C { get; set; }
        public decimal ID_PLAYMAU { get; set; }
        public Nullable<int> ID_Phieuxetnghiem_C { get; set; }
        public string SoTB { get; set; }
        public string KiemdinhH { get; set; }
        public string KiemdinhT1 { get; set; }
        public string KiemDinhT2 { get; set; }
        public Nullable<byte> Chatluong { get; set; }
        public Nullable<byte> Taymau { get; set; }
        public Nullable<byte> Dosach { get; set; }
        public Nullable<byte> DoDay { get; set; }
        public Nullable<byte> Kichco { get; set; }
        public Nullable<byte> Domin { get; set; }
        public string Ghichu { get; set; }
        public string GhichuKD1 { get; set; }
        public string GhichuKD2 { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
