//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_VW_PHIEUNHAP_TONGHOP
    {
        public Nullable<int> THANG { get; set; }
        public int ID_VATTU { get; set; }
        public Nullable<decimal> TONG_NHAP { get; set; }
        public long ID_KHONHAP { get; set; }
        public int NAM { get; set; }
        public string LO_SANXUAT { get; set; }
    }
}
