//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_KD_BC_KIEMDINHTB
    {
        public decimal ID_KiemdinhTB { get; set; }
        public byte Quy { get; set; }
        public int Nam { get; set; }
        public string ID_Benhvien { get; set; }
        public Nullable<int> TSTBThuchien { get; set; }
        public Nullable<int> TSTBCanthuchien { get; set; }
        public Nullable<int> SoTBKiemdinh { get; set; }
        public Nullable<int> SaiDlon { get; set; }
        public Nullable<int> SaiAlon { get; set; }
        public Nullable<int> DLLon { get; set; }
        public Nullable<int> SaiDNho { get; set; }
        public Nullable<int> SaiANho { get; set; }
        public Nullable<int> DLNho { get; set; }
        public Nullable<int> CLBPDat { get; set; }
        public Nullable<int> TaymauDat { get; set; }
        public Nullable<int> DosachDat { get; set; }
        public Nullable<int> DodayDat { get; set; }
        public Nullable<int> KichthuocDat { get; set; }
        public Nullable<int> DominDat { get; set; }
        public Nullable<System.DateTime> Ngay_NM { get; set; }
        public string Nguoi_NM { get; set; }
        public Nullable<bool> PTNhap { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public string NguoiBC { get; set; }
        public Nullable<int> Loilon { get; set; }
        public Nullable<int> Loinho { get; set; }
        public Nullable<int> TongsoTBKiemdinh { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
