//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_PHIEUXETNGHIEM_C
    {
        public int ID_Phieuxetnghiem_C { get; set; }
        public int ID_Phieuxetnghiem { get; set; }
        public string SoXN { get; set; }
        public Nullable<System.DateTime> NgayNhanMau { get; set; }
        public string TrangthaiDom { get; set; }
        public byte Maudom { get; set; }
        public Nullable<byte> Ketqua { get; set; }
    }
}
