//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_KIEMKE_CHITIET
    {
        public decimal ID_KIEMKE_CHITIET { get; set; }
        public decimal ID_KIEMKE { get; set; }
        public int ID_VATTU { get; set; }
        public int ID_TRANGTHAI { get; set; }
        public decimal SO_LUONG { get; set; }
        public string LO_SANXUAT { get; set; }
        public Nullable<System.DateTime> HAN_SUDUNG { get; set; }
    
        public virtual NTP_QLVT_DM_TRANGTHAI NTP_QLVT_DM_TRANGTHAI { get; set; }
        public virtual NTP_QLVT_DM_VATTU NTP_QLVT_DM_VATTU { get; set; }
        public virtual NTP_QLVT_KIEMKE NTP_QLVT_KIEMKE { get; set; }
    }
}
