//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_VW_ALL_NHAPXUAT
    {
        public long ID_KHO { get; set; }
        public int ID_NGUONKINHPHI { get; set; }
        public int ID_LYDO_NHAPXUAT { get; set; }
        public int ID_VATTU { get; set; }
        public System.DateTime NGAY_NHAP { get; set; }
        public string SO_CHUNGTU { get; set; }
        public decimal SO_LUONG { get; set; }
        public string TYPE { get; set; }
        public string LO_SANXUAT { get; set; }
        public Nullable<System.DateTime> HAN_SUDUNG { get; set; }
    }
}
