//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_KD_BC_HOATDONGXN
    {
        public decimal ID_HOATDONGXN { get; set; }
        public byte Quy { get; set; }
        public int Nam { get; set; }
        public string ID_BENHVIEN { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<int> SoTBPhathienD { get; set; }
        public Nullable<int> SoTBPhathienA { get; set; }
        public Nullable<int> SoTBTheodoiD { get; set; }
        public Nullable<int> SoTBTheodoiA { get; set; }
        public Nullable<System.DateTime> NgayBC { get; set; }
        public string NguoiBC { get; set; }
        public Nullable<bool> PTNhap { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<System.DateTime> Ngay_NM { get; set; }
    }
}
