//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_CTCHONGLAOP3
    {
        public int ID_CTChonglaoP3 { get; set; }
        public int ID_CTChonglao { get; set; }
        public Nullable<bool> Phanloai { get; set; }
        public int ID_NguonNhanLuc { get; set; }
        public Nullable<int> NLHienco { get; set; }
        public Nullable<int> NLDaotao { get; set; }
        public Nullable<int> TongsoNLDaotao { get; set; }
        public string Ghichu { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
