//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLTB_View_XuatNhap
    {
        public System.DateTime Ngay_ChungTu { get; set; }
        public string TYPE { get; set; }
        public string SoChungTu { get; set; }
        public long Id_DonVi { get; set; }
        public Nullable<int> Id_NguonKinhPhi { get; set; }
        public int Id_Lydo_Nhapxuat { get; set; }
        public int Id_ThietBi { get; set; }
        public decimal So_Luong { get; set; }
        public int NAM { get; set; }
    }
}
