//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_KD_PLAYMAU
    {
        public decimal ID_PLAYMAU { get; set; }
        public Nullable<int> ThangLM { get; set; }
        public Nullable<int> Nam { get; set; }
        public string MA_TINH { get; set; }
        public string ID_BENHVIEN { get; set; }
        public string KTVien { get; set; }
        public string Nhanxet { get; set; }
        public Nullable<System.DateTime> NgayKD1 { get; set; }
        public string KDVien1 { get; set; }
        public string Nhanxet1 { get; set; }
        public Nullable<System.DateTime> NgayKD2 { get; set; }
        public string KDVien2 { get; set; }
        public string Nhanxet2 { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public Nullable<byte> PTNhap { get; set; }
        public Nullable<System.DateTime> NgayLM { get; set; }
        public Nullable<int> SoTBThuchien { get; set; }
        public Nullable<int> SoTBCanKD { get; set; }
        public Nullable<bool> Huy { get; set; }
    }
}
