//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_QLVT_DM_KHO
    {
        public NTP_QLVT_DM_KHO()
        {
            this.NTP_QLVT_KHO = new HashSet<NTP_QLVT_KHO>();
            this.NTP_QLVT_KY_KIEMKE_CHITIET = new HashSet<NTP_QLVT_KY_KIEMKE_CHITIET>();
            this.NTP_QLVT_PHIEUXUAT = new HashSet<NTP_QLVT_PHIEUXUAT>();
        }
    
        public long ID_KHO { get; set; }
        public string MA_KHO { get; set; }
        public string TEN_KHO { get; set; }
        public Nullable<int> ID_VUNG { get; set; }
        public Nullable<long> ID_KHO_CAPTREN { get; set; }
        public string DIA_CHI { get; set; }
        public string MA_HUYEN { get; set; }
        public string MA_TINH { get; set; }
        public Nullable<int> ID_MIEN { get; set; }
        public Nullable<int> ID_CAP { get; set; }
    
        public virtual NTP_DM_CAP NTP_DM_CAP { get; set; }
        public virtual NTP_DM_HUYEN NTP_DM_HUYEN { get; set; }
        public virtual NTP_DM_TINH NTP_DM_TINH { get; set; }
        public virtual NTP_DM_VUNG NTP_DM_VUNG { get; set; }
        public virtual ICollection<NTP_QLVT_KHO> NTP_QLVT_KHO { get; set; }
        public virtual ICollection<NTP_QLVT_KY_KIEMKE_CHITIET> NTP_QLVT_KY_KIEMKE_CHITIET { get; set; }
        public virtual ICollection<NTP_QLVT_PHIEUXUAT> NTP_QLVT_PHIEUXUAT { get; set; }
    }
}
