//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTP_BN_DIEUTRI
    {
        public decimal ID_Dieutri { get; set; }
        public string ID_BENHNHAN { get; set; }
        public string SoDKDT { get; set; }
        public string DVDieutri { get; set; }
        public Nullable<System.DateTime> NgayVV { get; set; }
        public Nullable<System.DateTime> NgayDT { get; set; }
        public Nullable<int> ID_PHANLOAIYTE { get; set; }
        public string DVGioiThieu { get; set; }
        public Nullable<int> ID_PhanLoaiBenh { get; set; }
        public Nullable<int> ID_PhanLoaiBN { get; set; }
        public Nullable<System.DateTime> NgayChupXQ { get; set; }
        public Nullable<byte> KetquaXQ { get; set; }
        public Nullable<byte> XNHIV1 { get; set; }
        public Nullable<byte> XNHIV2 { get; set; }
        public Nullable<byte> ART { get; set; }
        public Nullable<byte> CPT { get; set; }
        public string LymPho { get; set; }
        public string GiamSatDT { get; set; }
        public Nullable<int> ID_KetquaDT { get; set; }
        public Nullable<System.DateTime> NgayRV { get; set; }
        public string Ghichu { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public Nullable<System.DateTime> Ngay_SD { get; set; }
        public Nullable<int> Nguoi_SD { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public Nullable<int> ID_DieutriChuyen { get; set; }
        public Nullable<byte> ID_PhacdoDT { get; set; }
        public string PhacdoKhac { get; set; }
        public string Chandoan { get; set; }
        public Nullable<bool> HUY { get; set; }
        public Nullable<System.DateTime> NGAYHUY { get; set; }
        public string MaBNQL { get; set; }
        public Nullable<byte> ID_PhacdoTD { get; set; }
        public string PhacdoTDKhac { get; set; }
        public Nullable<int> Tuoi { get; set; }
    }
}
