//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PXN2
    {
        public decimal STT { get; set; }
        public string ID_BENHNHAN { get; set; }
        public string HOTEN { get; set; }
        public string SOCMND { get; set; }
        public string MaBNQL { get; set; }
        public Nullable<int> TUOI { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string TENGIOITINH { get; set; }
        public string TENTINH { get; set; }
        public string TENHUYEN { get; set; }
        public string DIACHI { get; set; }
    }
}
