//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_PhieuXetNghiem_KQ
    {
        public long ID_Phieuxetnghiem_C { get; set; }
        public long ID_PhieuXetNghiem { get; set; }
        public string SoXN { get; set; }
        public byte MauDom { get; set; }
        public Nullable<System.DateTime> NgayNhanMau { get; set; }
        public string TrangThaiDom { get; set; }
        public Nullable<byte> KetQua { get; set; }
    }
}
