//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_PhieuXetNghiem
    {
        public long ID_PhieuXetNghiem { get; set; }
        public long ID_Benhnhan { get; set; }
        public string SoXN { get; set; }
        public string ID_Benhvien { get; set; }
        public Nullable<int> ID_PhanloaiYte { get; set; }
        public int LydoXN { get; set; }
        public Nullable<byte> Soluong { get; set; }
        public Nullable<byte> SoThangDT { get; set; }
        public Nullable<byte> HIV { get; set; }
        public string SoDKDT { get; set; }
        public string XNVien { get; set; }
        public Nullable<System.DateTime> NGAY_NM { get; set; }
        public Nullable<int> NGUOI_NM { get; set; }
        public Nullable<bool> HuyenXN { get; set; }
        public Nullable<bool> TinhXN { get; set; }
        public string DV_XETNGHIEM { get; set; }
        public Nullable<System.DateTime> NgayXN { get; set; }
        public Nullable<bool> HUY { get; set; }
        public Nullable<System.DateTime> NGAYHUY { get; set; }
        public string DV_TiepNhan { get; set; }
        public Nullable<bool> Tiepnhan { get; set; }
    }
}
