//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SoKhamBenh
    {
        public long ID_SoKhamBenh { get; set; }
        public long ID_BENHNHAN { get; set; }
        public string TrieuChung { get; set; }
        public string KetQuaXetNghiemDom { get; set; }
        public string TrangThaiDomDaiThe { get; set; }
        public Nullable<int> SoMauDom { get; set; }
        public Nullable<System.DateTime> NgayXetNghiemDom { get; set; }
        public string XQ { get; set; }
        public Nullable<System.DateTime> NgayChupXQ { get; set; }
        public string Khac { get; set; }
        public string NoiGioiThieu { get; set; }
        public string ToChongLao { get; set; }
        public string XuTri { get; set; }
        public string BSKhamBenh { get; set; }
        public string Ghichu { get; set; }
        public Nullable<System.DateTime> NgayKhamBenh { get; set; }
        public Nullable<bool> HuyenKB { get; set; }
        public Nullable<bool> TinhKB { get; set; }
        public Nullable<bool> HUY { get; set; }
        public Nullable<System.DateTime> NGAYHUY { get; set; }
        public string MaBNQL { get; set; }
    }
}
