//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO_SoDieuTri_KQ
    {
        public decimal ID_Xetnghiem_GD { get; set; }
        public decimal ID_Dieutri { get; set; }
        public decimal ID_Phieuxetnghiem_C { get; set; }
        public byte ThoiGianDT { get; set; }
        public Nullable<System.DateTime> Ngayxn { get; set; }
        public string SoXN { get; set; }
        public Nullable<int> KetquaXN { get; set; }
        public Nullable<int> CanNang { get; set; }
        public string Nuoicay { get; set; }
        public System.DateTime NGAY_NM { get; set; }
        public int NGUOI_NM { get; set; }
        public Nullable<int> GeneXpert { get; set; }
    }
}
